/*
 * File: app/store/DeptRevenueStore.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.store.DeptRevenueStore', {
    extend: 'Ext.data.Store',
    alias: 'store.deptrevenuestore',

    requires: [
        'CarePortal.model.DepartmentRevenue',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'DeptRevenueStore',
            model: 'CarePortal.model.DepartmentRevenue',
            proxy: {
                type: 'ajax',
                url: 'data/getDataFunctions.php?task=getDeptsRevenue',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});