/*
 * File: app/store/MembersListStore.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.store.MembersListStore', {
    extend: 'Ext.data.Store',
    alias: 'store.membersliststore',

    requires: [
        'CarePortal.model.MembersLists',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            pageSize: 700,
            storeId: 'MembersListStore',
            model: 'CarePortal.model.MembersLists',
            proxy: {
                type: 'ajax',
                url: 'data/debtorFunctions.php?task=getMembersList',
                reader: {
                    type: 'json',
                    rootProperty: 'memberslist'
                }
            }
        }, cfg)]);
    }
});