/*
 * File: app/view/AccountSection.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.view.AccountSection', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.accountsection',

    requires: [
        'CarePortal.view.AccountSectionViewModel',
        'CarePortal.view.AccountSectionViewController',
        'Ext.view.Table',
        'Ext.grid.column.Column',
        'Ext.toolbar.Paging'
    ],

    controller: 'accountsection',
    viewModel: {
        type: 'accountsection'
    },
    columnLines: true,
    store: 'AccountSectionStore',

    columns: [
        {
            xtype: 'gridcolumn',
            dataIndex: 'sectionid',
            text: 'Section ID'
        },
        {
            xtype: 'gridcolumn',
            width: 284,
            dataIndex: 'sectionname',
            text: 'Section Name'
        }
    ],
    dockedItems: [
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            width: 360,
            displayInfo: true,
            store: 'AccountSectionStore'
        }
    ],
    listeners: {
        afterrender: 'onAccountSectionAfterRender'
    }

});