/*
 * File: app/view/Admissions.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.view.Admissions', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.admissions',

    requires: [
        'CarePortal.view.AdmissionsViewModel',
        'Ext.view.Table',
        'Ext.grid.column.Column',
        'Ext.toolbar.Paging',
        'Ext.form.FieldSet',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Checkbox',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'admissions'
    },
    height: 600,
    itemId: 'Admissions',
    resizable: true,
    scrollable: 'both',
    width: 1156,
    columnLines: true,
    store: 'AdmissionsStore',

    columns: [
        {
            xtype: 'gridcolumn',
            dataIndex: 'pid',
            text: 'Pid'
        },
        {
            xtype: 'gridcolumn',
            width: 248,
            dataIndex: 'names',
            text: 'Names'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'encounter_nr',
            text: 'Encounter Nr'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'encounter_class_nr',
            text: 'Admission Type'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'dob',
            text: 'Dob'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'admTime',
            text: 'Adm Date'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'disTime',
            text: 'Dis Date'
        },
        {
            xtype: 'gridcolumn',
            width: 186,
            dataIndex: 'ward',
            text: 'Ward'
        },
        {
            xtype: 'gridcolumn',
            width: 186,
            dataIndex: 'totalInvoice',
            text: 'Total'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'phone',
            text: 'Phone'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'idNo',
            text: 'ID No'
        }
    ],
    dockedItems: [
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            width: 360,
            displayInfo: true,
            store: 'AdmissionsStore'
        },
        {
            xtype: 'fieldset',
            dock: 'top',
            height: 44,
            padding: 0,
            width: 100,
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'textfield',
                    itemId: 'txtSearchParam',
                    margin: 5,
                    width: 281
                },
                {
                    xtype: 'combobox',
                    itemId: 'admType',
                    margin: 5,
                    width: 153,
                    emptyText: 'Amission Type',
                    displayField: 'admType',
                    minChars: 2,
                    queryMode: 'local',
                    store: [
                        {
                            admType: 'Inpatient',
                            value: 'IP'
                        },
                        {
                            admType: 'Inpatient',
                            value: 'OP'
                        }
                    ],
                    typeAhead: true,
                    valueField: 'value'
                },
                {
                    xtype: 'checkboxfield',
                    itemId: 'discharged',
                    margin: 5,
                    boxLabel: 'Show Discharged',
                    inputValue: '1',
                    uncheckedValue: '0'
                },
                {
                    xtype: 'button',
                    itemId: 'cmdPreviewIpReports',
                    margin: 5,
                    width: 120,
                    iconCls: 'x-fa fa-search',
                    text: 'Search'
                },
                {
                    xtype: 'textfield',
                    itemId: 'formStatus'
                }
            ]
        }
    ]

});