/*
 * File: app/view/Allergies.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.view.Allergies', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.allergies',

    requires: [
        'CarePortal.view.AllergiesViewModel',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.panel.Panel'
    ],

    viewModel: {
        type: 'allergies'
    },
    layout: 'absolute',
    title: 'Allergies',

    items: [
        {
            xtype: 'combobox',
            x: 5,
            y: 5,
            itemId: 'allergyName',
            width: 220,
            labelAlign: 'right',
            labelStyle: 'color:green; font-weight:bold;',
            name: 'allergyName',
            submitValue: false,
            fieldStyle: 'color:#630921; font-weight:bold;',
            emptyText: 'Allergy Name'
        },
        {
            xtype: 'textfield',
            x: 230,
            y: 5,
            itemId: 'allergyDescription',
            width: 345,
            labelAlign: 'right',
            labelStyle: 'color:green; font-weight:bold;',
            name: 'allergyDescription',
            submitValue: false,
            fieldStyle: 'color:#630921; font-weight:bold;',
            emptyText: 'Description'
        },
        {
            xtype: 'button',
            x: 580,
            y: 5,
            itemId: 'cmdAddAllergies',
            iconCls: 'x-fa fa-plus',
            text: 'Add'
        },
        {
            xtype: 'panel',
            x: 5,
            y: 40,
            height: 110,
            itemId: 'allergiesPanel'
        }
    ]

});