/*
 * File: app/view/AnaesthesiaRecordGrid.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.view.AnaesthesiaRecordGrid', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.anaesthesiarecordgrid',

    requires: [
        'CarePortal.view.undefinedViewModel18',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.column.Boolean',
        'Ext.view.Table',
        'Ext.panel.Tool'
    ],

    viewModel: {
        type: 'anaesthesiarecordgrid'
    },
    minHeight: 600,
    minWidth: 1000,
    animCollapse: true,
    closable: true,
    collapsible: true,
    title: 'Anaesthesia Records',

    columns: [
        {
            xtype: 'gridcolumn',
            dataIndex: 'string',
            text: 'String'
        },
        {
            xtype: 'numbercolumn',
            dataIndex: 'number',
            text: 'Number'
        },
        {
            xtype: 'datecolumn',
            dataIndex: 'date',
            text: 'Date'
        },
        {
            xtype: 'booleancolumn',
            dataIndex: 'bool',
            text: 'Boolean'
        }
    ],
    tools: [
        {
            xtype: 'tool',
            type: 'maximize'
        },
        {
            xtype: 'tool',
            type: 'minimize'
        }
    ]

});