/*
 * File: app/view/CreateDentalService.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.view.CreateDentalService', {
    extend: 'Ext.form.Panel',
    alias: 'widget.createdentalservice',

    requires: [
        'CarePortal.view.ServicesViewModel4',
        'CarePortal.view.PatientDetais',
        'CarePortal.view.ServicesProcedures',
        'Ext.form.FieldSet',
        'Ext.form.field.ComboBox',
        'Ext.form.field.TextArea',
        'Ext.button.Button',
        'Ext.grid.Panel'
    ],

    viewModel: {
        type: 'createdentalservice'
    },
    height: 525,
    itemId: 'DentalServices',
    width: 944,
    bodyPadding: 1,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    dockedItems: [
        {
            xtype: 'patientdetais',
            dock: 'top',
            flex: 1
        }
    ],
    items: [
        {
            xtype: 'fieldset',
            flex: 0,
            margin: 2,
            padding: 0,
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'combobox',
                    flex: 2,
                    margins: '',
                    itemId: 'Services',
                    margin: '2 5 2 2',
                    name: 'Services',
                    fieldStyle: 'color:#630921; font-weight:bold;',
                    emptyText: 'Services',
                    displayField: 'Description',
                    minChars: 2,
                    queryMode: 'local',
                    store: 'DentalServices',
                    typeAhead: true,
                    valueField: 'PartCode'
                },
                {
                    xtype: 'textfield',
                    flex: 0,
                    itemId: 'Qty',
                    margin: '2 5 2 2',
                    width: 97,
                    name: 'Qty',
                    fieldStyle: 'color:#630921; font-weight:bold;',
                    emptyText: 'Frequency'
                },
                {
                    xtype: 'textfield',
                    flex: 0,
                    itemId: 'Price',
                    margin: '2 5 2 2',
                    fieldLabel: 'Price',
                    labelAlign: 'right',
                    labelStyle: 'color:maroon; font-weight:bold;',
                    labelWidth: 50,
                    name: 'Price',
                    fieldStyle: 'color:#630921; font-weight:bold;',
                    emptyText: 'Price'
                }
            ]
        },
        {
            xtype: 'fieldset',
            flex: 0,
            margin: 2,
            padding: 0,
            layout: 'hbox',
            items: [
                {
                    xtype: 'textareafield',
                    flex: 2,
                    margins: '',
                    itemId: 'Comments',
                    margin: '2 5 2 2',
                    name: 'Comments',
                    fieldStyle: 'color:#630921; font-weight:bold;',
                    emptyText: 'Comments'
                },
                {
                    xtype: 'button',
                    itemId: 'cmdAddServices',
                    iconCls: 'x-fa fa-plus',
                    text: 'Add Services'
                }
            ]
        },
        {
            xtype: 'servicesprocedures',
            flex: 1
        }
    ]

});