/*
 * File: app/view/Discharges.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.view.Discharges', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.discharges',

    requires: [
        'CarePortal.view.AdmissionsViewModel1',
        'Ext.view.Table',
        'Ext.toolbar.Paging',
        'Ext.form.FieldSet',
        'Ext.form.field.Date',
        'Ext.button.Button',
        'Ext.selection.RowModel',
        'Ext.grid.column.Widget'
    ],

    viewModel: {
        type: 'discharges'
    },
    itemId: 'Discharges',
    columnLines: true,
    store: 'DischargesStore',

    dockedItems: [
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            width: 360,
            displayInfo: true,
            store: 'DischargesStore'
        },
        {
            xtype: 'fieldset',
            dock: 'top',
            height: 44,
            padding: 0,
            width: 100,
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'textfield',
                    itemId: 'txtSearchParam',
                    margin: 5,
                    width: 455
                },
                {
                    xtype: 'datefield',
                    itemId: 'startDate',
                    margin: 5,
                    fieldLabel: 'Start Date',
                    labelAlign: 'right',
                    labelStyle: 'color:green; font-weight:bold;'
                },
                {
                    xtype: 'datefield',
                    itemId: 'startDate1',
                    margin: 5,
                    fieldLabel: 'End Date',
                    labelAlign: 'right',
                    labelStyle: 'color:green; font-weight:bold;'
                },
                {
                    xtype: 'button',
                    itemId: 'cmdPreviewIpReports',
                    margin: 5,
                    width: 120,
                    iconCls: 'x-fa fa-search',
                    text: 'Search'
                },
                {
                    xtype: 'textfield',
                    itemId: 'formStatus',
                    margin: 5
                }
            ]
        }
    ],
    columns: [
        {
            xtype: 'gridcolumn',
            width: 80,
            dataIndex: 'pid',
            text: 'Pid'
        },
        {
            xtype: 'gridcolumn',
            width: 250,
            dataIndex: 'names',
            text: 'Names'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'encounter_nr',
            text: 'Encounter Nr'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'dob',
            text: 'Dob'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'admDate',
            text: 'Adm Date'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'admTime',
            text: 'Adm Time'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'disDate',
            text: 'Dis Date'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'disTime',
            text: 'Dis Time'
        },
        {
            xtype: 'gridcolumn',
            width: 84,
            dataIndex: 'relDate',
            text: 'Bed Days'
        },
        {
            xtype: 'gridcolumn',
            width: 196,
            dataIndex: 'ward',
            text: 'Ward'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'phone',
            text: 'Phone'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'totalInvoice',
            text: 'Id No'
        },
        {
            xtype: 'widgetcolumn',
            dataIndex: 'pid',
            text: 'Discharge Summary',
            widget: {
                xtype: 'button',
                bind: '{record.pid}',
                itemId: 'cmdDischargeSummary',
                resizable: false,
                iconCls: 'widget-grid-user',
                text: 'Summary',
                tooltip: 'Discharge Summary'
            }
        },
        {
            xtype: 'widgetcolumn',
            dataIndex: 'pid',
            text: 'Notes',
            widget: {
                xtype: 'button',
                bind: '{record.pid}',
                itemId: 'cmdDischargeNotes',
                text: 'Notes',
                tooltip: 'Nursing Notes',
                tooltipType: 'title'
            }
        }
    ],
    selModel: {
        selType: 'rowmodel'
    }

});