/*
 * File: app/view/DoctorsArea.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.view.DoctorsArea', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.doctorsarea',

    requires: [
        'CarePortal.view.DoctorsAreaViewModel',
        'CarePortal.view.StatisticsPanel',
        'CarePortal.view.OpWaitingList',
        'CarePortal.view.DoctorsNotes',
        'CarePortal.view.VitalsLists',
        'CarePortal.view.ServicesProcedures',
        'CarePortal.view.Diagnosis',
        'CarePortal.view.Investigations',
        'CarePortal.view.DosageList',
        'Ext.form.Panel',
        'Ext.grid.Panel'
    ],

    viewModel: {
        type: 'doctorsarea'
    },
    baseCls: '',
    cls: 'x-portal',
    frame: true,
    scrollable: true,
    ui: 'light-framed-framed',
    bodyCls: 'x-portal-body',
    frameHeader: false,

    items: [
        {
            xtype: 'statisticspanel'
        },
        {
            xtype: 'form',
            layout: 'column',
            items: [
                {
                    xtype: 'container',
                    columnWidth: 0.33333,
                    padding: '5 3 3 1',
                    layout: 'anchor',
                    items: [
                        {
                            xtype: 'opwaitinglist',
                            height: 393,
                            margin: '0 0 10 0'
                        },
                        {
                            xtype: 'doctorsnotes',
                            draggable: true,
                            height: 319,
                            itemId: 'notesPanel',
                            closable: true,
                            collapsible: true
                        }
                    ]
                },
                {
                    xtype: 'container',
                    columnWidth: 0.33333,
                    padding: '5 3 3 3',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'vitalslists',
                            height: 140
                        },
                        {
                            xtype: 'servicesprocedures',
                            height: 233,
                            title: 'Procedures and Services',
                            flex: 1
                        },
                        {
                            xtype: 'diagnosis',
                            flex: 1
                        }
                    ]
                },
                {
                    xtype: 'container',
                    columnWidth: 0.33333,
                    padding: '5 5 5 5',
                    toFrontOnShow: false,
                    layout: 'anchor',
                    items: [
                        {
                            xtype: 'investigations',
                            draggable: true,
                            closable: true,
                            collapsible: true
                        },
                        {
                            xtype: 'dosagelist'
                        }
                    ]
                }
            ]
        }
    ]

});