/*
 * File: app/view/DrugsIssued.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.view.DrugsIssued', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.drugsissued',

    requires: [
        'CarePortal.view.DrugsIssuedViewModel',
        'Ext.view.Table',
        'Ext.grid.column.Column',
        'Ext.toolbar.Paging',
        'Ext.form.field.Text'
    ],

    viewModel: {
        type: 'drugsissued'
    },
    itemId: 'DrugsIssued',
    store: 'DrugsIssuedStore',

    columns: [
        {
            xtype: 'gridcolumn',
            dataIndex: 'id',
            text: 'ID'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'presc_nr',
            text: 'Presc Nr'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'order_date',
            text: 'Order Date'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'order_time',
            text: 'Order Time'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'store_loc',
            text: 'Store Loc'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'adm_no',
            text: 'Adm No'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'patient_name',
            text: 'Patient Name'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'item_id',
            text: 'Item Id'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'Item_desc',
            text: 'Item Desc'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'qty',
            text: 'Qty'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'price',
            text: 'Price'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'unit_cost',
            text: 'Unit Cost'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'issued',
            text: 'Issued'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'balance',
            text: 'Balance'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'total',
            text: 'Total'
        }
    ],
    dockedItems: [
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            width: 360,
            displayInfo: true,
            store: 'DrugsIssuedStore'
        },
        {
            xtype: 'container',
            dock: 'top',
            height: 43,
            padding: 5,
            width: 100,
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'textfield',
                    margin: '0 0 5 0',
                    width: 320,
                    emptyText: 'Search issued drugs by PID,Patient,Drugs.......'
                }
            ]
        }
    ]

});