/*
 * File: app/view/InvoicePanel.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.view.InvoicePanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.invoicepanel',

    requires: [
        'CarePortal.view.InvoicePanelViewModel',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.form.CheckboxGroup',
        'Ext.form.field.Checkbox',
        'Ext.button.Button',
        'Ext.form.FieldSet'
    ],

    viewModel: {
        type: 'invoicepanel'
    },
    itemId: 'InvoicePanel',
    minHeight: 1020,
    scrollable: 'vertical',
    bodyStyle: 'background:#386d87',
    defaultListenerScope: true,

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'form',
            height: 113,
            padding: 0,
            layout: 'absolute',
            bodyStyle: 'background:#386d87',
            items: [
                {
                    xtype: 'combobox',
                    x: -14,
                    y: 5,
                    itemId: 'invoiceType',
                    width: 485,
                    fieldLabel: 'Invoice Type',
                    labelAlign: 'right',
                    labelStyle: 'font-weight:bold; color:#f4f6fc;',
                    fieldStyle: 'color:#630921; font-weight:bold;',
                    emptyText: 'Select Invoice Type',
                    store: [
                        'Interim Detail Invoice',
                        'Interim Summary Invoice',
                        'Final Detail Invoice',
                        'Final Summary Invoice'
                    ]
                },
                {
                    xtype: 'combobox',
                    x: -14,
                    y: 75,
                    itemId: 'txtBillNumber',
                    width: 315,
                    fieldLabel: 'Bill Number',
                    labelAlign: 'right',
                    labelStyle: 'font-weight:bold; color:#f4f6fc;',
                    fieldStyle: 'color:#630921; font-weight:bold;',
                    allowBlank: false,
                    emptyText: 'Select Invoice Number',
                    displayField: 'BillNumbers',
                    minChars: 2,
                    queryMode: 'local',
                    store: 'BillNumbersStore',
                    typeAhead: true,
                    valueField: 'BillNumbers',
                    listeners: {
                        change: 'onTxtBillNumberChange'
                    }
                },
                {
                    xtype: 'textfield',
                    x: -14,
                    y: 40,
                    itemId: 'txtInvoicePid',
                    width: 195,
                    fieldLabel: 'Pid',
                    labelAlign: 'right',
                    labelStyle: 'font-weight:bold; color:#f4f6fc;',
                    fieldStyle: 'color:#630921; font-weight:bold;',
                    allowBlank: false,
                    emptyText: 'Enter Pid'
                },
                {
                    xtype: 'textfield',
                    x: 180,
                    y: 40,
                    itemId: 'txtPatientName',
                    width: 290,
                    fieldStyle: 'color:#630921; font-weight:bold;',
                    allowBlank: false,
                    emptyText: 'Patient Name'
                },
                {
                    xtype: 'checkboxgroup',
                    x: 550,
                    y: 5,
                    style: 'color:Green; font-weight:bold;',
                    width: 190,
                    layout: 'anchor',
                    labelAlign: 'right',
                    labelStyle: 'color:Green; font-weight:bold;',
                    items: [
                        {
                            xtype: 'checkboxfield',
                            itemId: 'includeReceipt',
                            style: 'color:Green; font-weight:bold;',
                            fieldLabel: 'include Receipt Payments',
                            labelAlign: 'right',
                            labelStyle: 'font-weight:bold; color:#f4f6fc;',
                            labelWidth: 180,
                            fieldStyle: 'color:Green; font-weight:bold;',
                            boxLabel: ''
                        },
                        {
                            xtype: 'checkboxfield',
                            itemId: 'includeNhif',
                            fieldLabel: 'Include NHIF Credits',
                            labelAlign: 'right',
                            labelStyle: 'font-weight:bold; color:#f4f6fc;',
                            labelWidth: 180,
                            fieldStyle: 'font-weight:bold; color:#f4f6fc;',
                            boxLabel: ''
                        }
                    ]
                },
                {
                    xtype: 'button',
                    x: 780,
                    y: 10,
                    formBind: true,
                    itemId: 'cmdPreviewInvoice',
                    width: 100,
                    icon: 'f570',
                    iconCls: 'x-fa fa-inbox',
                    text: 'Preview'
                },
                {
                    xtype: 'button',
                    x: 900,
                    y: 10,
                    formBind: true,
                    itemId: 'cmdPrintIpInvoice',
                    width: 165,
                    iconCls: 'x-fa fa-print',
                    text: 'Print A4 Invoice Size'
                },
                {
                    xtype: 'button',
                    x: 1080,
                    y: 10,
                    formBind: true,
                    width: 160,
                    iconCls: 'x-fa fa-print',
                    text: 'Print Mini Invoice'
                },
                {
                    xtype: 'textfield',
                    x: 640,
                    y: 75,
                    itemId: 'encNr',
                    fieldLabel: 'Encounter No',
                    labelStyle: 'font-weight:bold; color:#f4f6fc;',
                    labelWidth: 95
                },
                {
                    xtype: 'textfield',
                    x: 935,
                    y: 75,
                    itemId: 'formStatus',
                    labelStyle: 'font-weight:bold; color:#f4f6fc;',
                    labelWidth: 95
                },
                {
                    xtype: 'button',
                    x: 475,
                    y: 40,
                    itemId: 'cmdSearchAdmissions',
                    width: 95,
                    iconCls: 'x-fa fa-search',
                    text: 'Search'
                }
            ]
        },
        {
            xtype: 'fieldset',
            flex: 1,
            html: '<div id=invoiceDetails>Invoice will be displayed here....</div>',
            itemId: 'invoiceDetails',
            scrollable: 'vertical',
            style: 'border:1;'
        }
    ],

    onTxtBillNumberChange: function(field, newValue, oldValue, eOpts) {
        Ext.Ajax.request({
            url: 'data/getReportsData.php?task=getEncounterFromBill',
            params: {
                billNumber:newValue
            },
            waitMsg: 'getting encounteNo ...',
            success: function(response){
                var encDetails= Ext.util.JSON.decode(response.responseText);
                field.up('panel').down('#encNr').setValue(encDetails[0].encounter_nr);
            },
            failure:function(response){
                var resp = JSON.parse(response);
                Ext.Msg.alert('Error',resp.Error);

                //                     Ext.Msg.alert('Error','There was a problem deleting the Part Locations, Contact System Administrator');
            }
        });
    }

});