/*
 * File: app/view/InvoicesList.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.view.InvoicesList', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.invoiceslist',

    requires: [
        'CarePortal.view.InvoicesListViewModel',
        'Ext.view.Table',
        'Ext.toolbar.Paging',
        'Ext.grid.column.Column',
        'Ext.form.field.Date',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'invoiceslist'
    },
    itemId: 'InvoicesList',
    columnLines: true,

    dockedItems: [
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            width: 360,
            displayInfo: true
        },
        {
            xtype: 'container',
            dock: 'top',
            height: 44,
            width: 100,
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'textfield',
                    margin: 5,
                    width: 302
                },
                {
                    xtype: 'datefield',
                    margin: 5,
                    fieldLabel: 'Start Date',
                    labelAlign: 'right',
                    labelStyle: 'color:green; font-weight:bold;'
                },
                {
                    xtype: 'datefield',
                    margin: 5,
                    fieldLabel: 'End Date',
                    labelAlign: 'right',
                    labelStyle: 'color:green; font-weight:bold;'
                },
                {
                    xtype: 'button',
                    itemId: 'cmdPreviewIpReports',
                    margin: 5,
                    width: 141,
                    iconCls: 'x-fa fa-search',
                    text: 'Preview'
                }
            ]
        }
    ],
    columns: [
        {
            xtype: 'gridcolumn',
            width: 76,
            dataIndex: 'Pid',
            text: 'Pid'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'EncounterNo',
            text: 'Encounter No'
        },
        {
            xtype: 'gridcolumn',
            width: 217,
            dataIndex: 'Names',
            text: 'Names'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'AdmissionDate',
            text: 'Admission Date'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'BillNumber',
            text: 'Bill Number'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'BedDays',
            text: 'Bed Days'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'Bill',
            text: 'Bill'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'Payment',
            text: 'Payment'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'Balance',
            text: 'Balance'
        },
        {
            xtype: 'gridcolumn',
            width: 215,
            dataIndex: 'PayementMode',
            text: 'Payement Mode'
        }
    ]

});