/*
 * File: app/view/ItemRegister.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.view.ItemRegister', {
    extend: 'Ext.form.Panel',
    alias: 'widget.itemregister',

    requires: [
        'CarePortal.view.ItemRegisterViewModel',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.FieldSet',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Checkbox',
        'Ext.form.field.TextArea'
    ],

    viewModel: {
        type: 'itemregister'
    },
    height: 593,
    width: 826,
    layout: 'absolute',
    bodyPadding: 10,
    url: 'data/getDataFunctions.php?task=InsertItem',

    items: [
        {
            xtype: 'button',
            x: 185,
            y: 535,
            itemId: 'cmdSaveProducts',
            width: 95,
            iconCls: 'x-fa fa-save',
            text: 'Save'
        },
        {
            xtype: 'button',
            x: 565,
            y: 535,
            itemId: 'cmdClose',
            width: 95,
            iconCls: 'x-fa fa-close',
            text: 'Cancel'
        },
        {
            xtype: 'tabpanel',
            x: 5,
            y: 5,
            frame: true,
            height: 520,
            width: 815,
            activeTab: 0,
            items: [
                {
                    xtype: 'panel',
                    height: 487,
                    width: 811,
                    layout: 'absolute',
                    title: 'Item Details',
                    items: [
                        {
                            xtype: 'fieldset',
                            x: 0,
                            y: 5,
                            height: 375,
                            width: 450,
                            items: [
                                {
                                    xtype: 'textfield',
                                    height: 10,
                                    fieldLabel: 'PartCode',
                                    labelStyle: 'color:green; font-weight:bold;',
                                    labelWidth: 110,
                                    name: 'PartCode',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textfield',
                                    width: 418,
                                    fieldLabel: 'Description',
                                    labelStyle: 'color:green; font-weight:bold;',
                                    labelWidth: 110,
                                    name: 'Item_Description',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textfield',
                                    width: 417,
                                    fieldLabel: 'Long Description',
                                    labelStyle: 'color:green; font-weight:bold;',
                                    labelWidth: 110,
                                    name: 'Item_Full_Description',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'combobox',
                                    fieldLabel: 'Unit of Measure',
                                    labelStyle: 'color:green; font-weight:bold;',
                                    labelWidth: 110,
                                    name: 'Unit_Measure',
                                    allowBlank: false,
                                    displayField: 'Name',
                                    minChars: 2,
                                    queryMode: 'local',
                                    store: 'UnitsMeasureStore',
                                    typeAhead: true,
                                    valueField: 'Name'
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Purchasing Units',
                                    labelStyle: 'color:green; font-weight:bold;',
                                    labelWidth: 110,
                                    name: 'Purchasing_Unit',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Units Quantity',
                                    labelStyle: 'color:green; font-weight:bold;',
                                    labelWidth: 110,
                                    name: 'Unit_Qty',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'combobox',
                                    width: 416,
                                    fieldLabel: 'Category',
                                    labelStyle: 'color:green; font-weight:bold;',
                                    labelWidth: 110,
                                    name: 'Purchasing_Class',
                                    allowBlank: false,
                                    displayField: 'CatName',
                                    minChars: 2,
                                    queryMode: 'local',
                                    store: 'CategoryStore',
                                    typeAhead: true,
                                    valueField: 'CatName'
                                },
                                {
                                    xtype: 'combobox',
                                    width: 417,
                                    fieldLabel: 'Sub Category',
                                    labelStyle: 'color:green; font-weight:bold;',
                                    labelWidth: 110,
                                    name: 'Category',
                                    allowBlank: false,
                                    displayField: 'ItemCat',
                                    minChars: 2,
                                    queryMode: 'local',
                                    store: 'SubCategoryStore',
                                    typeAhead: true,
                                    valueField: 'CatID'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            x: 460,
                            y: 5,
                            height: 460,
                            width: 355,
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'Selling Price',
                                    labelStyle: 'color:green; font-weight:bold;',
                                    name: 'Unit_Price',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'Buying Price',
                                    labelStyle: 'color:green; font-weight:bold;',
                                    name: 'buying_price',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'Reorder Level',
                                    labelStyle: 'color:green; font-weight:bold;',
                                    name: 'Reorderlevel'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'Minimum Order',
                                    labelStyle: 'color:green; font-weight:bold;',
                                    name: 'Minimum'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'Maximum Order',
                                    labelStyle: 'color:green; font-weight:bold;',
                                    name: 'Maximum'
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: 'Prescription Level',
                                    labelStyle: 'color:green; font-weight:bold;',
                                    name: 'PresLevel',
                                    minChars: 2,
                                    queryMode: 'local',
                                    store: [
                                        'Level1',
                                        'Level2',
                                        'Level3'
                                    ],
                                    typeAhead: true
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: 'Prescription NHIF',
                                    labelStyle: 'color:green; font-weight:bold;',
                                    name: 'PresNHIF',
                                    allowBlank: false,
                                    minChars: 2,
                                    queryMode: 'local',
                                    store: [
                                        'Yes',
                                        'No'
                                    ],
                                    typeAhead: true
                                },
                                {
                                    xtype: 'combobox',
                                    anchor: '100%',
                                    fieldLabel: 'Item Status',
                                    labelStyle: 'color:green; font-weight:bold;',
                                    name: 'Item_Status',
                                    allowBlank: false,
                                    displayField: 'Description',
                                    minChars: 2,
                                    queryMode: 'local',
                                    store: 'ItemStatusStore',
                                    typeAhead: true,
                                    valueField: 'ID'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    anchor: '100%',
                                    formBind: false,
                                    itemId: 'stockItem',
                                    fieldLabel: 'Is Stock Item',
                                    labelStyle: 'color:green; font-weight:bold;',
                                    name: 'stockItem',
                                    checked: true,
                                    inputValue: 'Yes',
                                    uncheckedValue: 'No'
                                }
                            ]
                        },
                        {
                            xtype: 'textareafield',
                            x: 5,
                            y: 385,
                            height: 82,
                            width: 435,
                            fieldLabel: 'More Info',
                            labelStyle: 'color:green; font-weight:bold;',
                            name: 'MoreInfo'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    height: 341,
                    bodyPadding: '10 1 1 20',
                    title: 'Accounting Details',
                    items: [
                        {
                            xtype: 'combobox',
                            fieldLabel: 'Sales GL Account',
                            labelWidth: 110,
                            name: 'Gl_Sales_Acct',
                            displayField: 'AccountName',
                            minChars: 2,
                            queryMode: 'local',
                            typeAhead: true,
                            valueField: 'AccountCode'
                        },
                        {
                            xtype: 'combobox',
                            fieldLabel: 'Cost of Sales GL',
                            labelWidth: 110,
                            name: 'Gl_CostOfSales_Acct',
                            displayField: 'AccountName',
                            minChars: 2,
                            queryMode: 'local',
                            typeAhead: true,
                            valueField: 'AccountCode'
                        },
                        {
                            xtype: 'combobox',
                            fieldLabel: 'Inventory GL',
                            labelWidth: 110,
                            name: 'Gl_Inventory_Acct',
                            displayField: 'AccountName',
                            minChars: 2,
                            queryMode: 'local',
                            typeAhead: true,
                            valueField: 'AccountCode'
                        },
                        {
                            xtype: 'combobox',
                            fieldLabel: 'Sales Area',
                            labelWidth: 110,
                            name: 'SalesAreas',
                            displayField: 'Description',
                            minChars: 2,
                            typeAhead: true,
                            valueField: 'ID'
                        },
                        {
                            xtype: 'textfield',
                            hidden: true,
                            itemId: 'formStatus',
                            labelWidth: 110,
                            name: 'formStatus'
                        },
                        {
                            xtype: 'checkboxfield',
                            fieldLabel: 'Charge Item During Admission',
                            labelWidth: 200,
                            name: 'ChargeInAdmission',
                            inputValue: 'Yes',
                            uncheckedValue: 'No'
                        },
                        {
                            xtype: 'checkboxfield',
                            fieldLabel: 'Show as Consultation Admission Data',
                            labelWidth: 200,
                            name: 'isConsultation',
                            inputValue: 'Yes',
                            uncheckedValue: 'No'
                        }
                    ]
                }
            ]
        }
    ]

});