/*
 * File: app/view/MCH.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.view.MCH', {
    extend: 'Ext.form.Panel',
    alias: 'widget.mch',

    requires: [
        'CarePortal.view.MCHViewModel',
        'CarePortal.view.PatientDetais',
        'Ext.form.FieldSet',
        'Ext.button.Button',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date'
    ],

    viewModel: {
        type: 'mch'
    },
    height: 607,
    bodyPadding: 10,
    url: 'data/getDataFunctions.php?task=saveMch',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'container',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'patientdetais',
                    margin: '0 0 2 0',
                    flex: 0
                },
                {
                    xtype: 'container',
                    flex: 0,
                    margin: '0 0 2 0',
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'cmdSaveMch',
                            width: 124,
                            iconCls: 'x-fa fa-save',
                            text: 'Save'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    itemId: 'mchForms',
                    scrollable: 'vertical',
                    items: [
                        {
                            xtype: 'fieldset',
                            margin: '0 0 0 0',
                            padding: '0 0 0 10',
                            collapsed: true,
                            collapsible: true,
                            title: 'CWC',
                            layout: {
                                type: 'vbox',
                                align: 'stretchmax'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    flex: 0,
                                    margin: '0 0 2 0',
                                    fieldLabel: 'Weight',
                                    labelAlign: 'right',
                                    name: 'weight'
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '0 0 2 0',
                                    fieldLabel: 'Height',
                                    labelAlign: 'right',
                                    name: 'height'
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '0 0 2 0',
                                    fieldLabel: 'Age',
                                    labelAlign: 'right',
                                    name: 'age'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 2,
                                    fieldLabel: 'TCA (Notes)',
                                    labelAlign: 'right',
                                    name: 'notes'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 2,
                                    fieldLabel: 'TCA (Notes)',
                                    labelAlign: 'right',
                                    name: 'mch_type',
                                    value: 'CWC'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            margin: 0,
                            padding: '0 0 0 10',
                            collapsed: true,
                            collapsible: true,
                            title: 'ANC',
                            layout: {
                                type: 'vbox',
                                align: 'stretchmax'
                            },
                            items: [
                                {
                                    xtype: 'combobox',
                                    flex: 0,
                                    margin: '0 0 2 0',
                                    fieldLabel: 'Visit Status',
                                    labelAlign: 'right',
                                    labelWidth: 120,
                                    name: 'anc_visit_status',
                                    store: [
                                        'New',
                                        'ReVisit'
                                    ]
                                },
                                {
                                    xtype: 'datefield',
                                    margin: '0 0 2 0',
                                    fieldLabel: 'Date of Birth',
                                    labelAlign: 'right',
                                    labelWidth: 120,
                                    name: 'dob'
                                },
                                {
                                    xtype: 'textfield',
                                    margins: '0 0 2 0',
                                    margin: '0 0 2 0',
                                    fieldLabel: 'LMP',
                                    labelAlign: 'right',
                                    labelWidth: 120,
                                    name: 'lmp'
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '0 0 2 0',
                                    fieldLabel: 'EDD',
                                    labelAlign: 'right',
                                    labelWidth: 120,
                                    name: 'edd'
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '0 0 2 0',
                                    fieldLabel: 'Gestation in Weeks',
                                    labelAlign: 'right',
                                    labelWidth: 120,
                                    name: 'gestation_in_weeks'
                                },
                                {
                                    xtype: 'combobox',
                                    margin: '0 0 2 0',
                                    fieldLabel: 'HIV',
                                    labelAlign: 'right',
                                    labelWidth: 120,
                                    name: 'HIV',
                                    store: [
                                        'Positive',
                                        'Negative',
                                        'Pre-N',
                                        'Pre-P'
                                    ]
                                },
                                {
                                    xtype: 'combobox',
                                    margin: '0 0 2 0',
                                    fieldLabel: 'HAART Given',
                                    labelAlign: 'right',
                                    labelWidth: 120,
                                    name: 'Haart',
                                    store: [
                                        'Yes',
                                        'No'
                                    ]
                                },
                                {
                                    xtype: 'combobox',
                                    margin: '0 0 2 0',
                                    fieldLabel: 'Infant Prophylaxis',
                                    labelAlign: 'right',
                                    labelWidth: 120,
                                    name: 'InfantProphylaxis',
                                    store: [
                                        'Yes',
                                        'No'
                                    ]
                                },
                                {
                                    xtype: 'combobox',
                                    margin: '0 0 2 0',
                                    fieldLabel: 'Partner Testing',
                                    labelAlign: 'right',
                                    labelWidth: 120,
                                    name: 'PartnerTesting',
                                    store: [
                                        'Yes',
                                        'No',
                                        'N/A'
                                    ]
                                },
                                {
                                    xtype: 'combobox',
                                    margin: '0 0 2 0',
                                    fieldLabel: 'Partner Testing Results',
                                    labelAlign: 'right',
                                    labelWidth: 120,
                                    name: 'PartnerTestingResults',
                                    store: [
                                        'Positive',
                                        'Negative',
                                        'N/A'
                                    ]
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '0 0 2 0',
                                    fieldLabel: 'Other Conditions',
                                    labelAlign: 'right',
                                    labelWidth: 120,
                                    name: 'OtherConditions'
                                },
                                {
                                    xtype: 'combobox',
                                    margin: '0 0 2 0',
                                    fieldLabel: 'Preventive Services',
                                    labelAlign: 'right',
                                    labelWidth: 120,
                                    name: 'PreventiveServices',
                                    store: [
                                        'Tetanus',
                                        'IPTp-SP',
                                        'LLITN',
                                        'Dewarming',
                                        'Suplementation'
                                    ]
                                },
                                {
                                    xtype: 'datefield',
                                    flex: 2,
                                    fieldLabel: 'TCA (Notes)',
                                    labelAlign: 'right',
                                    labelWidth: 120,
                                    name: 'TCA'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 2,
                                    fieldLabel: 'TCA (Notes)',
                                    labelAlign: 'right',
                                    labelWidth: 120,
                                    name: 'Remarks',
                                    value: 'ANC'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            padding: '0 0 0 10',
                            collapsible: true,
                            title: 'Family Planning',
                            layout: {
                                type: 'vbox',
                                align: 'stretchmax'
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    flex: 0,
                                    margins: '0 0 2 0',
                                    margin: '0 0 2 0',
                                    fieldLabel: 'Weight',
                                    labelAlign: 'right',
                                    labelWidth: 140,
                                    name: 'fpWeight'
                                },
                                {
                                    xtype: 'combobox',
                                    margin: '0 0 2 0',
                                    fieldLabel: 'Previous Method Used',
                                    labelAlign: 'right',
                                    labelWidth: 140,
                                    name: 'previous_method_used',
                                    store: [
                                        'Condom',
                                        'Diaphragm',
                                        'Pills',
                                        'Implants',
                                        'Injections',
                                        'IUD',
                                        'Female Condom'
                                    ]
                                },
                                {
                                    xtype: 'combobox',
                                    margin: '0 0 2 0',
                                    fieldLabel: 'Curent Method',
                                    labelAlign: 'right',
                                    labelWidth: 140,
                                    name: 'current_method',
                                    store: [
                                        'Condom',
                                        'Diaphragm',
                                        'Pills',
                                        'Implants',
                                        'Injections',
                                        'IUD',
                                        'Female Condom'
                                    ]
                                },
                                {
                                    xtype: 'combobox',
                                    margin: '0 0 2 0',
                                    fieldLabel: 'HIV Status',
                                    labelAlign: 'right',
                                    labelWidth: 140,
                                    name: 'HIVStatus',
                                    store: [
                                        'Condom',
                                        'Diaphragm',
                                        'Pills',
                                        'Implants',
                                        'Injections',
                                        'IUD',
                                        'Female Condom'
                                    ]
                                },
                                {
                                    xtype: 'combobox',
                                    margin: '0 0 2 0',
                                    fieldLabel: 'HIV Status',
                                    labelAlign: 'right',
                                    labelWidth: 140,
                                    name: 'HIVStatus',
                                    store: [
                                        'Condom',
                                        'Diaphragm',
                                        'Pills',
                                        'Implants',
                                        'Injections',
                                        'IUD',
                                        'Female Condom'
                                    ]
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '0 0 2 0',
                                    fieldLabel: 'BP',
                                    labelAlign: 'right',
                                    labelWidth: 140,
                                    name: 'BP'
                                },
                                {
                                    xtype: 'datefield',
                                    flex: 2,
                                    fieldLabel: 'TCA (Notes)',
                                    labelAlign: 'right',
                                    labelWidth: 140,
                                    name: 'notes'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 2,
                                    fieldLabel: 'Remaks',
                                    labelAlign: 'right',
                                    labelWidth: 140,
                                    name: 'mch_type'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            padding: '0 0 0 10',
                            collapsed: true,
                            collapsible: true,
                            title: 'PNC',
                            layout: {
                                type: 'vbox',
                                align: 'stretchmax'
                            },
                            items: [
                                {
                                    xtype: 'combobox',
                                    flex: 0,
                                    margins: '0 0 2 0',
                                    margin: '0 0 2 0',
                                    fieldLabel: 'Timing Of Visit',
                                    labelAlign: 'right',
                                    labelWidth: 140,
                                    name: 'TimingOfVisit',
                                    store: [
                                        
                                    ]
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 0,
                                    margins: '0 0 2 0',
                                    margin: '0 0 2 0',
                                    fieldLabel: 'General Condtion',
                                    labelAlign: 'right',
                                    labelWidth: 140,
                                    name: 'GeneralCondtion'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 0,
                                    margins: '0 0 2 0',
                                    margin: '0 0 2 0',
                                    fieldLabel: 'Mother BP',
                                    labelAlign: 'right',
                                    labelWidth: 140,
                                    name: 'motherBP'
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '0 0 2 0',
                                    fieldLabel: 'Baby Temp',
                                    labelAlign: 'right',
                                    labelWidth: 140,
                                    name: 'Baby_temp'
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '0 0 2 0',
                                    fieldLabel: 'Cord Status',
                                    labelAlign: 'right',
                                    labelWidth: 140,
                                    name: 'cord_status'
                                },
                                {
                                    xtype: 'textfield',
                                    margin: '0 0 2 0',
                                    fieldLabel: 'Cord Status',
                                    labelAlign: 'right',
                                    labelWidth: 140,
                                    name: 'BreastExam'
                                },
                                {
                                    xtype: 'combobox',
                                    margin: '0 0 2 0',
                                    fieldLabel: 'Cord Status',
                                    labelAlign: 'right',
                                    labelWidth: 140,
                                    name: 'CSScar',
                                    store: [
                                        'Yes',
                                        'No',
                                        'N/A'
                                    ]
                                },
                                {
                                    xtype: 'combobox',
                                    margin: '0 0 2 0',
                                    fieldLabel: 'Cord Status',
                                    labelAlign: 'right',
                                    labelWidth: 140,
                                    name: 'InvolutionOfUterus',
                                    store: [
                                        'Yes',
                                        'No',
                                        'N/A'
                                    ]
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 2,
                                    fieldLabel: 'TCA (Notes)',
                                    labelAlign: 'right',
                                    labelWidth: 140,
                                    name: 'notes'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 2,
                                    fieldLabel: 'TCA (Notes)',
                                    labelAlign: 'right',
                                    labelWidth: 140,
                                    name: 'mch_type',
                                    value: 'PNC'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});