/*
 * File: app/view/Notes.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.view.Notes', {
    extend: 'Ext.form.Panel',
    alias: 'widget.notes',

    requires: [
        'CarePortal.view.NotesViewModel',
        'CarePortal.view.NotesList',
        'Ext.form.FieldSet',
        'Ext.form.field.Display',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.form.field.HtmlEditor',
        'Ext.grid.Panel',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'notes'
    },
    height: 510,
    width: 976,
    bodyPadding: 5,

    dockedItems: [
        {
            xtype: 'fieldset',
            dock: 'top',
            height: 47,
            style: 'background:#386d87',
            width: 744,
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'displayfield',
                    itemId: 'pid',
                    width: 83,
                    fieldLabel: 'PID',
                    labelStyle: 'font-weight:bold; color:#f4f6fc;',
                    labelWidth: 30,
                    fieldStyle: 'color:#a7e88b;font-weight-bold;'
                },
                {
                    xtype: 'displayfield',
                    itemId: 'names',
                    width: 230,
                    fieldLabel: 'Names',
                    labelPad: 0,
                    labelStyle: 'font-weight:bold; color:#f4f6fc;',
                    labelWidth: 60,
                    fieldStyle: 'color:#a7e88b;font-weight-bold;'
                },
                {
                    xtype: 'displayfield',
                    itemId: 'encounterNo',
                    width: 211,
                    fieldLabel: 'Encounter No',
                    labelStyle: 'font-weight:bold; color:#f4f6fc;',
                    name: 'encounter_nr',
                    fieldStyle: 'color:#a7e88b;font-weight-bold;',
                    readOnly: true
                },
                {
                    xtype: 'displayfield',
                    itemId: 'Dob',
                    width: 239,
                    fieldLabel: 'Date of Birth',
                    labelStyle: 'font-weight:bold; color:#f4f6fc;',
                    fieldStyle: 'color:#a7e88b;font-weight-bold;'
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'container',
            height: 393,
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'container',
                    flex: 0,
                    width: 227,
                    items: [
                        {
                            xtype: 'radiogroup',
                            itemId: 'type_nr',
                            width: 225,
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'radiofield',
                                    boxLabel: '<b>Chief Complaints</b>',
                                    inputValue: '1'
                                },
                                {
                                    xtype: 'radiofield',
                                    boxLabel: '<b>Medical/Family/Social History</b>',
                                    inputValue: '2'
                                },
                                {
                                    xtype: 'radiofield',
                                    boxLabel: '<b>History Presenting Illness</b>',
                                    inputValue: '6'
                                },
                                {
                                    xtype: 'radiofield',
                                    boxLabel: '<b>Medications & Allergies</b>',
                                    inputValue: '22'
                                },
                                {
                                    xtype: 'radiofield',
                                    boxLabel: '<b>Review of Symtoms</b>',
                                    inputValue: '4'
                                },
                                {
                                    xtype: 'radiofield',
                                    boxLabel: '<b>Physical Exams</b>',
                                    inputValue: '5'
                                },
                                {
                                    xtype: 'radiofield',
                                    boxLabel: '<b>Investigations</b>',
                                    inputValue: '10'
                                },
                                {
                                    xtype: 'radiofield',
                                    boxLabel: '<b>Plan</b>',
                                    inputValue: '7'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    height: 459,
                    items: [
                        {
                            xtype: 'fieldset',
                            height: 184,
                            padding: 5,
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'htmleditor',
                                    flex: 1,
                                    height: 191,
                                    itemId: 'notes',
                                    margin: '0 3 0 0',
                                    width: 403,
                                    labelAlign: 'top',
                                    name: 'notes'
                                }
                            ]
                        },
                        {
                            xtype: 'noteslist'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            height: 37,
            layout: 'absolute',
            items: [
                {
                    xtype: 'button',
                    x: 235,
                    y: 0,
                    width: 150,
                    iconCls: 'x-fa fa-sync',
                    text: 'Preview Note'
                },
                {
                    xtype: 'button',
                    x: 560,
                    y: 0,
                    height: 32,
                    itemId: 'cmdAddComplaints',
                    width: 140,
                    iconCls: 'x-fa fa-save',
                    text: 'Save'
                }
            ]
        }
    ]

});