/*
 * File: app/view/NotesList.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.view.NotesList', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.noteslist',

    requires: [
        'CarePortal.view.NotesListViewModel',
        'Ext.view.Table',
        'Ext.grid.column.Action'
    ],

    viewModel: {
        type: 'noteslist'
    },
    frame: true,
    height: 195,
    itemId: 'notesGrid',
    width: 754,
    columnLines: true,
    store: 'NotesStore',

    columns: [
        {
            xtype: 'gridcolumn',
            width: 167,
            dataIndex: 'CreateTime',
            text: 'Create Time'
        },
        {
            xtype: 'gridcolumn',
            width: 127,
            dataIndex: 'NotesType',
            text: 'Notes Type'
        },
        {
            xtype: 'gridcolumn',
            width: 302,
            dataIndex: 'Notes',
            text: 'Notes'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'TreatedBy',
            text: 'Treated By'
        },
        {
            xtype: 'actioncolumn',
            itemId: 'deleteNote',
            width: 37,
            align: 'center',
            items: [
                {
                    icon: 'icons/delete1.jpg'
                }
            ]
        }
    ]

});