/*
 * File: app/view/OutpatientReports.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.view.OutpatientReports', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.outpatientreports',

    requires: [
        'CarePortal.view.OutpatientReportsViewModel',
        'Ext.button.Segmented',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'outpatientreports'
    },

    items: [
        {
            xtype: 'segmentedbutton',
            padding: '5 0 5 5',
            width: 892,
            layout: 'anchor',
            items: [
                {
                    itemId: 'mnuOPMobidity',
                    margin: '10 0 0 10',
                    text: 'Daily OP Mobidity Report'
                },
                {
                    itemId: 'mnuOpVisits',
                    enableToggle: true,
                    pressed: true,
                    text: 'Outpatient Workload'
                },
                {
                    id: 'DiagnosisReport',
                    itemId: 'mnuDiagnosisReport',
                    text: 'Diagnosis Report'
                },
                {
                    itemId: 'mnuTopDiseases',
                    text: 'Top Diseases'
                },
                {
                    itemId: 'mnuDentalClinic',
                    text: 'Dental Clinic'
                },
                {
                    itemId: 'mnuHtc',
                    text: 'HTC Reports'
                },
                {
                    itemId: 'mnuWorkload',
                    text: 'Doctor Workload'
                },
                {
                    itemId: 'mnuCreditSlips',
                    margin: '10 0 0 10',
                    text: 'Credit Slips'
                },
                {
                    itemId: 'mnuOpInvoices',
                    enableToggle: true,
                    text: 'Outpatient Invoices'
                },
                {
                    itemId: 'mnuTreatmentReport',
                    text: 'HTN Treatment Register'
                }
            ]
        },
        {
            xtype: 'container',
            itemId: 'opReports'
        }
    ]

});