/*
 * File: app/view/PatientChart.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.view.PatientChart', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.patientchart',

    requires: [
        'CarePortal.view.PatientChartViewModel',
        'CarePortal.view.PatientChartViewController',
        'CarePortal.view.PatientDetails',
        'Ext.chart.CartesianChart',
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.chart.series.Line',
        'Ext.chart.interactions.PanZoom'
    ],

    controller: 'patientchart',
    viewModel: {
        type: 'patientchart'
    },
    height: 800,
    scrollable: 'both',
    width: 1200,

    items: [
        {
            xtype: 'patientdetails'
        },
        {
            xtype: 'cartesian',
            height: 628,
            scrollable: 'both',
            style: {
                stroke: '#666666',
                fillOpacity: 0.8
            },
            colors: [
                '#115fa6',
                '#94ae0a',
                '#a61120',
                '#ff8809',
                '#ffd13e',
                '#a61187',
                '#24ad9a',
                '#7c7474',
                '#a66111'
            ],
            legend: {
                type: 'sprite',
                docked: 'right'
            },
            store: 'VitalsChartStore',
            axes: [
                {
                    type: 'category',
                    grid: true,
                    position: 'bottom'
                },
                {
                    type: 'numeric',
                    grid: true,
                    maximum: 200,
                    minimum: 0,
                    position: 'left'
                }
            ],
            series: [
                {
                    type: 'line',
                    highlight: true,
                    highlightCfg: {
                        fillStyle: 'yellow',
                        strokeStyle: 'red',
                        scaling: 2
                    },
                    marker: {
                        type: 'triangle',
                        animation: {
                            duration: 200,
                            easing: 'backOut'
                        }
                    },
                    style: {
                        fill: '#115fa6',
                        stroke: '#115fa6',
                        fillOpacity: 0.6,
                        miterLimit: 3,
                        lineCap: 'miter',
                        lineWidth: 2
                    },
                    title: 'Temperature',
                    tooltip: {
                        trackMouse: true,
                        renderer: 'onSeriesTooltipRender'
                    },
                    xField: 'VitalsTime',
                    yField: [
                        'Temperature'
                    ]
                },
                {
                    type: 'line',
                    colors: [
                        '#115fa6',
                        '#94ae0a',
                        '#a61120',
                        '#ff8809',
                        '#ffd13e',
                        '#a61187',
                        '#24ad9a',
                        '#7c7474',
                        '#a66111'
                    ],
                    highlight: true,
                    highlightCfg: {
                        fillStyle: 'yellow',
                        strokeStyle: 'red',
                        scaling: 2
                    },
                    marker: {
                        type: 'square',
                        animation: {
                            duration: 200,
                            easing: 'backOut'
                        }
                    },
                    style: {
                        smooth: true,
                        stroke: '#94ae0a',
                        fillOpacity: 0.6,
                        miterLimit: 3,
                        lineCap: 'miter',
                        lineWidth: 2
                    },
                    title: 'Systolic',
                    tooltip: {
                        trackMouse: true,
                        renderer: 'onSeriesTooltipRender'
                    },
                    xField: 'VitalsTime',
                    yField: [
                        'Systolic'
                    ]
                },
                {
                    type: 'line',
                    colors: [
                        '#115fa6',
                        '#94ae0a',
                        '#a61120',
                        '#ff8809',
                        '#ffd13e',
                        '#a61187',
                        '#24ad9a',
                        '#7c7474',
                        '#a66111'
                    ],
                    highlight: true,
                    highlightCfg: {
                        fillStyle: 'yellow',
                        strokeStyle: 'red',
                        scaling: 2
                    },
                    marker: {
                        type: 'square',
                        animation: {
                            duration: 200,
                            easing: 'backOut'
                        }
                    },
                    style: {
                        smooth: true,
                        stroke: '#a61120',
                        fillOpacity: 0.6,
                        miterLimit: 3,
                        lineCap: 'miter',
                        lineWidth: 2
                    },
                    title: 'Diastolic',
                    tooltip: {
                        trackMouse: true,
                        renderer: 'onSeriesTooltipRender'
                    },
                    xField: 'VitalsTime',
                    yField: [
                        'Diastolic'
                    ]
                },
                {
                    type: 'line',
                    colors: [
                        '#115fa6',
                        '#94ae0a',
                        '#a61120',
                        '#ff8809',
                        '#ffd13e',
                        '#a61187',
                        '#24ad9a',
                        '#7c7474',
                        '#a66111'
                    ],
                    highlight: true,
                    highlightCfg: {
                        fillStyle: 'yellow',
                        strokeStyle: 'red',
                        scaling: 2
                    },
                    marker: {
                        type: 'arrow',
                        animation: {
                            duration: 200,
                            easing: 'backOut'
                        }
                    },
                    style: {
                        smooth: true,
                        stroke: '#a61187',
                        fillOpacity: 0.6,
                        miterLimit: 3,
                        lineCap: 'miter',
                        lineWidth: 2
                    },
                    title: 'Pulse Rate',
                    tooltip: {
                        trackMouse: true,
                        renderer: 'onSeriesTooltipRender'
                    },
                    xField: 'VitalsTime',
                    yField: [
                        'Pulse'
                    ]
                },
                {
                    type: 'line',
                    colors: [
                        '#115fa6',
                        '#94ae0a',
                        '#a61120',
                        '#ff8809',
                        '#ffd13e',
                        '#a61187',
                        '#24ad9a',
                        '#7c7474',
                        '#a66111'
                    ],
                    highlight: true,
                    highlightCfg: {
                        fillStyle: 'yellow',
                        strokeStyle: 'red',
                        scaling: 2
                    },
                    marker: {
                        type: 'cross',
                        animation: {
                            duration: 200,
                            easing: 'backOut'
                        }
                    },
                    style: {
                        smooth: true,
                        stroke: '#7c7474',
                        fillOpacity: 0.6,
                        miterLimit: 3,
                        lineCap: 'miter',
                        lineWidth: 2
                    },
                    title: 'Respiration',
                    tooltip: {
                        trackMouse: true,
                        renderer: 'onSeriesTooltipRender'
                    },
                    xField: 'VitalsTime',
                    yField: [
                        'Respiration'
                    ]
                }
            ],
            interactions: [
                {
                    type: 'panzoom',
                    zoomOnPan: true
                }
            ]
        }
    ]

});