/*
 * File: app/view/PatientsSummary.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.view.PatientsSummary', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.patientssummary',

    requires: [
        'CarePortal.view.PatientsSummaryViewModel',
        'CarePortal.view.ShiftsReportHeader',
        'Ext.view.Table',
        'Ext.grid.column.Column',
        'Ext.toolbar.Paging',
        'Ext.grid.feature.Summary'
    ],

    viewModel: {
        type: 'patientssummary'
    },
    itemId: 'PatientsSummary',
    columnLines: true,
    store: 'PatientsSummaryStore',

    columns: [
        {
            xtype: 'gridcolumn',
            dataIndex: 'ReceiptNo',
            text: 'Receipt No'
        },
        {
            xtype: 'gridcolumn',
            width: 178,
            dataIndex: 'Name',
            text: 'Name'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'Pay_Mode',
            text: 'Pay Mode'
        },
        {
            xtype: 'gridcolumn',
            summaryType: 'sum',
            dataIndex: 'Total',
            text: 'Total'
        },
        {
            xtype: 'gridcolumn',
            summaryType: 'sum',
            dataIndex: 'Cash',
            text: 'Cash'
        },
        {
            xtype: 'gridcolumn',
            summaryType: 'sum',
            dataIndex: 'Mpesa',
            text: 'Mpesa'
        },
        {
            xtype: 'gridcolumn',
            summaryType: 'sum',
            dataIndex: 'Visa',
            text: 'Visa'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'InputDate',
            text: 'Input Date'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'InputTime',
            text: 'Input Time'
        },
        {
            xtype: 'gridcolumn',
            summaryType: 'sum',
            dataIndex: 'Balance',
            text: 'Balance'
        }
    ],
    dockedItems: [
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            width: 360,
            displayInfo: true,
            store: 'PatientsSummaryStore'
        },
        {
            xtype: 'shiftsreportheader',
            dock: 'top'
        }
    ],
    features: [
        {
            ftype: 'summary'
        }
    ]

});