/*
 * File: app/view/PatientTransfer.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.view.PatientTransfer', {
    extend: 'Ext.form.Panel',
    alias: 'widget.patienttransfer',

    requires: [
        'CarePortal.view.undefinedViewModel5',
        'CarePortal.view.PatientDetails',
        'Ext.panel.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.Display',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.form.field.ComboBox'
    ],

    viewModel: {
        type: 'patienttransfer'
    },
    frame: true,
    width: 1005,
    bodyPadding: 3,

    items: [
        {
            xtype: 'patientdetails'
        },
        {
            xtype: 'fieldset',
            height: 33,
            margin: '5 0 5 0',
            padding: '0 0 0 15',
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'displayfield',
                    margin: '0 20 0 0',
                    labelStyle: 'color:#a7e88b;font-weight-bold;',
                    value: 'Where should the patient be transferred to?',
                    fieldStyle: 'color:maroon;font-weight:bold;font-size:14px;'
                },
                {
                    xtype: 'radiogroup',
                    flex: 1,
                    flex: 1,
                    itemId: 'transferWard',
                    width: 400,
                    items: [
                        {
                            xtype: 'radiofield',
                            name: 'transferWard',
                            boxLabel: '<b>Ward to Ward</b>',
                            inputValue: 'Wards'
                        },
                        {
                            xtype: 'radiofield',
                            name: 'transferWard',
                            boxLabel: '<b>Bed to Bed</b>',
                            inputValue: 'Beds'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'fieldset',
            height: 33,
            hidden: true,
            itemId: 'wardsList',
            margin: '5 0 5 0',
            padding: '0 0 0 15',
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'displayfield',
                    margin: '0 20 0 0',
                    labelStyle: 'color:#a7e88b;font-weight-bold;',
                    value: 'Select Ward to transfer to',
                    fieldStyle: 'color:maroon;font-weight:bold;font-size:14px;'
                },
                {
                    xtype: 'combobox',
                    flex: 0,
                    itemId: 'wardsList',
                    style: 'color:blue;font-weight:bold;font-size:14px;',
                    fieldStyle: 'color:blue;font-weight:bold;font-size:14px;',
                    displayField: 'Name',
                    minChars: 2,
                    queryMode: 'local',
                    store: 'WardsListStore',
                    typeAhead: true,
                    valueField: 'Nr'
                }
            ]
        },
        {
            xtype: 'fieldset',
            height: 564,
            itemId: 'transWindow',
            padding: '0 0 0 15'
        }
    ]

});