/*
 * File: app/view/PatientChartViewController.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.view.PatientChartViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.patientchart',

    onSeriesTooltipRender: function(tooltip, record, item) {
        var title = item.series.getTitle();

         //Ext.Msg.alert('test',record.get('VitalsTime'));
         tooltip.setHtml(title + ' at ' + record.get('VitalsTime') + ' was ' +record.get(item.series.getYField()));

    }

});
