/*
 * File: app/view/PendingPrescriptions.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.view.PendingPrescriptions', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.pendingprescriptions',

    requires: [
        'Ext.view.Table',
        'Ext.grid.feature.Grouping',
        'Ext.XTemplate',
        'Ext.toolbar.Paging',
        'Ext.form.FieldContainer',
        'Ext.form.field.ComboBox',
        'Ext.grid.column.Column'
    ],

    frame: true,
    height: 600,
    itemId: 'prescGrid',
    title: 'Pending Prescriptions',
    columnLines: true,
    store: 'PendingPrescription',
    defaultListenerScope: true,

    features: [
        {
            ftype: 'grouping',
            groupHeaderTpl: [
                '{columnName}: {name}  ({rows.length} Item{[values.rows.length > 1 ? "s" : ""]})'
            ]
        }
    ],
    dockedItems: [
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            width: 360,
            displayInfo: true,
            store: 'PendingPrescription'
        },
        {
            xtype: 'fieldcontainer',
            dock: 'top',
            height: 41,
            style: 'background-color: #d9f2e6;',
            width: 100,
            layout: 'absolute',
            items: [
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 5,
                    itemId: 'prescParams',
                    width: 145,
                    emptyText: 'Search By PID, Names'
                },
                {
                    xtype: 'combobox',
                    x: 160,
                    y: 5,
                    itemId: 'admSource',
                    width: 145,
                    emptyText: 'OP / IP',
                    store: [
                        'OP',
                        'IP'
                    ]
                }
            ]
        }
    ],
    columns: [
        {
            xtype: 'gridcolumn',
            dataIndex: 'Pid',
            text: 'Pid'
        },
        {
            xtype: 'gridcolumn',
            width: 262,
            dataIndex: 'Names',
            text: 'Names'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'EncounterNo',
            text: 'Encounter No'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'PrescribeDate',
            text: 'Prescribe Date'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'Nr',
            text: 'Nr'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'EncounterClassNr',
            text: 'Encounter Class Nr'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'Prescriber',
            text: 'Prescriber'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'PaymentMode',
            text: 'Payment Mode'
        }
    ],
    listeners: {
        afterrender: 'onPrescGridAfterRender'
    },

    onPrescGridAfterRender: function(component, eOpts) {

        var prescStore=Ext.data.StoreManager.lookup('PendingPrescription');
                prescStore.load({});
    }

});