/*
 * File: app/view/PrescriptionForm.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.view.PrescriptionForm', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.prescriptionform',

    requires: [
        'CarePortal.view.PrescriptionFormViewModel',
        'CarePortal.view.DrugsList',
        'CarePortal.view.DosageList',
        'Ext.grid.Panel',
        'Ext.form.Panel',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'prescripionform'
    },
    frame: true,
    height: 558,
    resizable: true,
    width: 1358,

    layout: {
        type: 'hbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'drugslist',
            width: 500,
            flex: 0
        },
        {
            xtype: 'form',
            flex: 0,
            frame: true,
            width: 61,
            layout: 'absolute',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'button',
                    x: 5,
                    y: 255,
                    text: '<<<'
                },
                {
                    xtype: 'button',
                    x: 5,
                    y: 190,
                    text: '>>>'
                }
            ]
        },
        {
            xtype: 'dosagelist',
            flex: 1
        }
    ]

});