/*
 * File: app/view/PurchaseOrderDetails.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.view.PurchaseOrderDetails', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.purchaseorderdetails',

    requires: [
        'CarePortal.view.PurchaseOrdersViewModel1',
        'Ext.view.Table',
        'Ext.toolbar.Paging',
        'Ext.button.Button',
        'Ext.grid.column.Column',
        'Ext.form.field.Number',
        'Ext.selection.RowModel',
        'Ext.grid.plugin.RowEditing'
    ],

    viewModel: {
        type: 'purchaseorderdetails'
    },
    height: 450,
    style: 'color:green;font-size:14px;',
    columnLines: true,
    store: 'PurchOrderItems',

    dockedItems: [
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            width: 360,
            displayInfo: true,
            store: 'PurchOrdersStore'
        },
        {
            xtype: 'container',
            dock: 'top',
            height: 40,
            width: 100,
            layout: 'absolute',
            items: [
                {
                    xtype: 'button',
                    x: 820,
                    y: 5,
                    itemId: 'newOrder',
                    width: 150,
                    iconCls: 'x-fa fa-pencil-square-o',
                    text: 'Update Changes'
                }
            ]
        }
    ],
    columns: [
        {
            xtype: 'gridcolumn',
            width: 44,
            dataIndex: 'ID',
            text: 'ID'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'OrderNo',
            text: 'Order No'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'PartCode',
            text: 'Part Code'
        },
        {
            xtype: 'gridcolumn',
            width: 285,
            dataIndex: 'ItemDescription',
            text: 'Item Description'
        },
        {
            xtype: 'gridcolumn',
            width: 139,
            dataIndex: 'QuantityOrd',
            text: 'Quantity Ord',
            editor: {
                xtype: 'numberfield'
            }
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'QtyInvoiced',
            text: 'Qty Invoiced'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'UnitPrice',
            text: 'Unit Price'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'ConversionFactor',
            text: 'Conversion Factor'
        },
        {
            xtype: 'gridcolumn',
            width: 122,
            dataIndex: 'QuantityRecd',
            text: 'Quantity Recd'
        }
    ],
    selModel: {
        selType: 'rowmodel'
    },
    plugins: [
        {
            ptype: 'rowediting'
        }
    ]

});