/*
 * File: app/view/Radiology.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.view.Radiology', {
    extend: 'Ext.form.Panel',
    alias: 'widget.radiology',

    requires: [
        'CarePortal.view.NotesViewModel3',
        'CarePortal.view.NotesViewController3',
        'Ext.form.FieldSet',
        'Ext.form.field.Display',
        'Ext.form.field.ComboBox',
        'Ext.button.Button'
    ],

    controller: 'radiology',
    viewModel: {
        type: 'radiology'
    },
    height: 469,
    width: 892,
    bodyPadding: 10,

    dockedItems: [
        {
            xtype: 'fieldset',
            dock: 'top',
            height: 45,
            style: 'background:#386d87',
            width: 744,
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'displayfield',
                    itemId: 'pid',
                    width: 83,
                    fieldLabel: 'PID',
                    labelStyle: 'font-weight:bold; color:#f4f6fc;',
                    labelWidth: 30,
                    fieldStyle: 'color:#a7e88b;font-weight-bold;'
                },
                {
                    xtype: 'displayfield',
                    itemId: 'names',
                    width: 230,
                    fieldLabel: 'Names',
                    labelPad: 0,
                    labelStyle: 'font-weight:bold; color:#f4f6fc;',
                    labelWidth: 60,
                    fieldStyle: 'color:#a7e88b;font-weight-bold;'
                },
                {
                    xtype: 'displayfield',
                    itemId: 'encounterNo',
                    width: 211,
                    fieldLabel: 'Encounter No',
                    labelStyle: 'font-weight:bold; color:#f4f6fc;',
                    name: 'encounter_nr',
                    fieldStyle: 'color:#a7e88b;font-weight-bold;',
                    readOnly: true
                },
                {
                    xtype: 'displayfield',
                    itemId: 'Dob',
                    width: 239,
                    fieldLabel: 'Date of Birth',
                    labelStyle: 'font-weight:bold; color:#f4f6fc;',
                    fieldStyle: 'color:#a7e88b;font-weight-bold;'
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'fieldset',
            padding: 5,
            layout: {
                type: 'hbox',
                align: 'stretchmax'
            },
            items: [
                {
                    xtype: 'combobox',
                    flex: 3,
                    itemId: 'Radiology',
                    margin: '0 5 0 0',
                    width: 340,
                    labelAlign: 'top',
                    fieldStyle: 'color:#630921; font-weight:bold;',
                    emptyText: 'X-Ray Requests',
                    displayField: 'Description',
                    minChars: 2,
                    queryMode: 'local',
                    store: 'RadiologyListStore',
                    typeAhead: true,
                    valueField: 'PartCode'
                },
                {
                    xtype: 'textfield',
                    flex: 1,
                    itemId: 'Price',
                    margin: '0 3 0 0',
                    width: 230,
                    labelAlign: 'top',
                    fieldStyle: 'color:#630921; font-weight:bold;',
                    emptyText: 'Price'
                },
                {
                    xtype: 'textfield',
                    flex: 2,
                    itemId: 'Comments',
                    margin: '0 3 0 0',
                    width: 230,
                    labelAlign: 'top',
                    fieldStyle: 'color:#630921; font-weight:bold;',
                    emptyText: 'Comments'
                },
                {
                    xtype: 'button',
                    height: 32,
                    itemId: 'cmdSaveRadiology',
                    text: 'Add X-Ray Request'
                }
            ]
        },
        {
            xtype: 'fieldset',
            height: 300,
            itemId: 'radiologyPanel'
        }
    ],
    listeners: {
        afterrender: 'onFormAfterRender'
    }

});