/*
 * File: app/view/Receipts.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.view.Receipts', {
    extend: 'Ext.form.Panel',
    alias: 'widget.receipts',

    requires: [
        'CarePortal.view.ReceiptsViewModel',
        'Ext.form.FieldSet',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.selection.RowModel',
        'Ext.grid.plugin.CellEditing',
        'Ext.grid.column.Action',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'receipts'
    },
    height: 624,
    itemId: 'receipts',
    style: 'background-color: #d9f2e6;',
    layout: 'border',
    bodyPadding: '1 0 0 4',
    bodyStyle: 'background-color: #d9f2e6;',
    url: 'data/getDataFunctions.php?task=saveCashReceipts',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'container',
            region: 'center',
            items: [
                {
                    xtype: 'fieldset',
                    height: 184,
                    padding: 0,
                    style: 'background-color: #d9f2e6;',
                    layout: 'absolute',
                    items: [
                        {
                            xtype: 'textfield',
                            x: 5,
                            y: 5,
                            itemId: 'CashPoint',
                            width: 205,
                            fieldLabel: 'Cash Point',
                            labelAlign: 'right',
                            labelStyle: 'color:green; font-weight:bold;',
                            name: 'cashPoint',
                            fieldStyle: 'color:red; font-weight:bold;',
                            readOnly: true,
                            allowBlank: false
                        },
                        {
                            xtype: 'combobox',
                            x: -46,
                            y: 40,
                            itemId: 'PayMode',
                            tabIndex: 0,
                            width: 255,
                            fieldLabel: 'Payment Mode',
                            labelAlign: 'right',
                            labelStyle: 'color:green; font-weight:bold;',
                            labelWidth: 150,
                            name: 'payMode',
                            allowBlank: false,
                            emptyText: 'Select department',
                            displayField: 'Description',
                            minChars: 2,
                            queryMode: 'local',
                            store: [
                                'Cash',
                                'Mpesa',
                                'Cheque',
                                'Both',
                                'Visa'
                            ],
                            typeAhead: true,
                            valueField: 'ID'
                        },
                        {
                            xtype: 'textfield',
                            x: 525,
                            y: 5,
                            itemId: 'ReceiptNo',
                            fieldLabel: 'Receipt No',
                            labelAlign: 'right',
                            labelStyle: 'color:green; font-weight:bold;',
                            labelWidth: 130,
                            name: 'receiptNo',
                            fieldStyle: 'color:red; font-weight:bold;',
                            readOnly: true,
                            emptyText: 'Receipt Number'
                        },
                        {
                            xtype: 'textfield',
                            x: 165,
                            y: 5,
                            itemId: 'ShiftNo',
                            fieldLabel: 'Shift No',
                            labelAlign: 'right',
                            labelStyle: 'color:green; font-weight:bold;',
                            labelWidth: 130,
                            name: 'shiftNo',
                            fieldStyle: 'color:red; font-weight:bold;',
                            readOnly: true,
                            emptyText: 'Shift Number'
                        },
                        {
                            xtype: 'textfield',
                            x: 525,
                            y: 75,
                            itemId: 'GlAccount',
                            fieldLabel: 'GL Account',
                            labelAlign: 'right',
                            labelStyle: 'color:green; font-weight:bold;',
                            labelWidth: 130,
                            name: 'glAccount',
                            fieldStyle: 'color:red; font-weight:bold;',
                            emptyText: 'GL Account'
                        },
                        {
                            xtype: 'textfield',
                            x: 525,
                            y: 110,
                            itemId: 'Bank',
                            fieldLabel: 'Drawers Bank',
                            labelAlign: 'right',
                            labelStyle: 'color:green; font-weight:bold;',
                            labelWidth: 130,
                            name: 'bank',
                            fieldStyle: 'color:red; font-weight:bold;',
                            emptyText: 'Drawers Bank'
                        },
                        {
                            xtype: 'textfield',
                            x: 525,
                            y: 145,
                            itemId: 'chequeNo',
                            fieldLabel: 'Cheque No',
                            labelAlign: 'right',
                            labelStyle: 'color:green; font-weight:bold;',
                            labelWidth: 130,
                            name: 'chequeNo',
                            fieldStyle: 'color:red; font-weight:bold;',
                            emptyText: 'Cheque No'
                        },
                        {
                            xtype: 'datefield',
                            x: 525,
                            y: 40,
                            itemId: 'CurrDate',
                            fieldLabel: 'Date',
                            labelAlign: 'right',
                            labelStyle: 'color:green; font-weight:bold;',
                            labelWidth: 130,
                            name: 'currDate',
                            fieldStyle: 'color:red; font-weight:bold;',
                            emptyText: 'Date'
                        },
                        {
                            xtype: 'textfield',
                            x: -27,
                            y: 110,
                            itemId: 'Payee',
                            tabIndex: 1,
                            width: 475,
                            fieldLabel: 'Payer',
                            labelAlign: 'right',
                            labelStyle: 'color:green; font-weight:bold;',
                            labelWidth: 130,
                            name: 'payer'
                        },
                        {
                            xtype: 'textfield',
                            x: -26,
                            y: 145,
                            itemId: 'Towards',
                            tabIndex: 2,
                            width: 475,
                            fieldLabel: 'Towards',
                            labelAlign: 'right',
                            labelStyle: 'color:green; font-weight:bold;',
                            labelWidth: 130,
                            name: 'towards'
                        },
                        {
                            xtype: 'textfield',
                            x: -45,
                            y: 75,
                            itemId: 'Pid',
                            width: 255,
                            fieldLabel: 'Patient',
                            labelAlign: 'right',
                            labelStyle: 'color:green; font-weight:bold;',
                            labelWidth: 150,
                            name: 'pid'
                        },
                        {
                            xtype: 'textfield',
                            x: 210,
                            y: 75,
                            itemId: 'PatientName',
                            width: 240,
                            labelAlign: 'right',
                            labelStyle: 'color:green; font-weight:bold;',
                            labelWidth: 150,
                            name: 'names'
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    reference: 'receiptsGrid',
                    height: 203,
                    itemId: 'receiptsGrid',
                    resizable: true,
                    columnLines: true,
                    store: 'LedgersStore',
                    viewConfig: {
                        tabIndex: 3
                    },
                    selModel: {
                        selType: 'rowmodel'
                    },
                    plugins: [
                        {
                            ptype: 'cellediting',
                            clicksToEdit: 1
                        }
                    ],
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'ledger',
                            text: 'Ledger'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'code',
                            text: 'Code'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 320,
                            dataIndex: 'Name',
                            text: 'Name'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                var strSum=0;
                                store.getRange().forEach(function(rec) {
                                    strSum += rec.get('Amount');
                                    console.log(rec.get('strSum'));
                                } );
                                view.up('grid').up('panel').down('#total').setValue(strSum);

                                return strSum;

                            },
                            dataIndex: 'Amount',
                            text: 'Amount',
                            editor: {
                                xtype: 'textfield'
                            }
                        },
                        {
                            xtype: 'actioncolumn',
                            text: 'Remove',
                            items: [
                                {
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                        Ext.MessageBox.confirm('Confirm', 'Are you sure you want to remove '+record.get('Description')+"?", function() {
                                            // process text value and close...
                                            view.getStore().remove(record);

                                        });

                                    },
                                    icon: 'icons/delete1.jpg'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    height: 178,
                    margin: 0,
                    padding: 0,
                    style: 'background-color: #d9f2e6;',
                    layout: 'absolute',
                    items: [
                        {
                            xtype: 'button',
                            x: 5,
                            y: 0,
                            itemId: 'cmdGetDebtors',
                            width: 145,
                            iconCls: 'x-fa fa-users',
                            text: 'Debtors Ledger'
                        },
                        {
                            xtype: 'button',
                            x: 155,
                            y: 0,
                            itemId: 'cmdGetSuppliers',
                            width: 145,
                            iconCls: 'x-fa fa-user',
                            text: 'Suppliers Ledger'
                        },
                        {
                            xtype: 'button',
                            x: 305,
                            y: 0,
                            itemId: 'cmdGetLedgers',
                            width: 145,
                            iconCls: 'x-fa fa-cog',
                            text: 'General Ledger'
                        },
                        {
                            xtype: 'textfield',
                            x: 440,
                            y: -0.6666670000000181,
                            itemId: 'total',
                            width: 230,
                            fieldLabel: 'Total',
                            labelAlign: 'right',
                            labelStyle: 'color:green; font-weight:bold;',
                            name: 'total'
                        },
                        {
                            xtype: 'textfield',
                            x: 440,
                            y: 105,
                            itemId: 'visa',
                            tabIndex: 7,
                            width: 230,
                            fieldLabel: 'Visa',
                            labelAlign: 'right',
                            labelStyle: 'color:green; font-weight:bold;',
                            name: 'visa'
                        },
                        {
                            xtype: 'textfield',
                            x: 440,
                            y: 140,
                            itemId: 'balance',
                            width: 230,
                            fieldLabel: 'Balance',
                            labelAlign: 'right',
                            labelStyle: 'color:green; font-weight:bold;',
                            name: 'balance',
                            readOnly: true
                        },
                        {
                            xtype: 'textfield',
                            x: 420,
                            y: 70,
                            itemId: 'mpesa',
                            tabIndex: 5,
                            width: 250,
                            fieldLabel: 'Received Mpesa',
                            labelAlign: 'right',
                            labelStyle: 'color:green; font-weight:bold;',
                            labelWidth: 120,
                            name: 'mpesa',
                            listeners: {
                                change: 'onMpesaChange'
                            }
                        },
                        {
                            xtype: 'textfield',
                            x: 670,
                            y: 70,
                            itemId: 'mpesa1',
                            tabIndex: 6,
                            width: 210,
                            fieldLabel: 'Mpesa Ref',
                            labelAlign: 'right',
                            labelStyle: 'color:green; font-weight:bold;',
                            labelWidth: 80,
                            name: 'mpesaRef'
                        },
                        {
                            xtype: 'textfield',
                            x: 440,
                            y: 35,
                            itemId: 'cash',
                            tabIndex: 4,
                            width: 230,
                            fieldLabel: 'Received Cash',
                            labelAlign: 'right',
                            labelStyle: 'color:green; font-weight:bold;',
                            name: 'cash',
                            listeners: {
                                change: 'onCashChange'
                            }
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    height: 43,
                    padding: 0,
                    style: 'background-color: #d9f2e6;',
                    layout: 'absolute',
                    items: [
                        {
                            xtype: 'button',
                            x: 545,
                            y: 5,
                            itemId: 'cmdSaveReceipt',
                            width: 120,
                            iconCls: 'x-fa fa-save',
                            text: 'Save'
                        },
                        {
                            xtype: 'button',
                            x: 715,
                            y: 5,
                            width: 130,
                            iconCls: 'x-fa fa-close',
                            text: 'Close'
                        }
                    ]
                }
            ]
        }
    ],

    onMpesaChange: function(field, newValue, oldValue, eOpts) {
        var total=field.up('form').down('#total').getValue();
        var cash=field.up('form').down('#cash').getValue();
        if(cash>0){
            var bal=parseInt(newValue)+parseInt(cash)-parseInt(total);
        }else{
            var bal=newValue-total;
        }

        field.up('form').down('#balance').setValue(bal);
    },

    onCashChange: function(field, newValue, oldValue, eOpts) {
        var total=field.up('form').down('#total').getValue();
        var bal=newValue-total;
        field.up('form').down('#balance').setValue(bal);

    }

});