/*
 * File: app/view/ResultsForm.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.view.ResultsForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.resultsform',

    requires: [
        'CarePortal.view.ResultsFormViewModel',
        'CarePortal.view.PatientDetailsLab',
        'Ext.panel.Panel',
        'Ext.form.FieldSet',
        'Ext.button.Button',
        'Ext.form.field.Text'
    ],

    viewModel: {
        type: 'resultsform'
    },
    height: 644,
    scrollable: 'both',
    width: 881,
    bodyPadding: 0,
    url: 'data/getDataFunctions.php?task=saveLabResults',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'patientdetailslab',
            flex: 0
        },
        {
            xtype: 'fieldset',
            itemId: 'resultsControl',
            layout: {
                type: 'vbox',
                align: 'stretch'
            }
        }
    ],
    dockedItems: [
        {
            xtype: 'container',
            dock: 'bottom',
            height: 46,
            layout: {
                type: 'hbox',
                align: 'stretch',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'button',
                    height: 40,
                    hidden: true,
                    itemId: 'cmdClose',
                    width: 120,
                    iconCls: 'x-fa fa-close',
                    text: 'Close'
                },
                {
                    xtype: 'button',
                    height: 40,
                    itemId: 'cmdSaveResults',
                    margin: '0 50 0 0',
                    width: 120,
                    iconCls: 'x-fa fa-save',
                    text: 'Save'
                },
                {
                    xtype: 'button',
                    height: 40,
                    itemId: 'cmdCloseResultsForm',
                    margin: '0 0 0 50',
                    width: 120,
                    iconCls: 'x-fa fa-close',
                    text: 'Close'
                },
                {
                    xtype: 'textfield',
                    hidden: true,
                    itemId: 'encNr',
                    width: 190,
                    fieldLabel: 'EncounterNr',
                    name: 'encounter_nr'
                },
                {
                    xtype: 'textfield',
                    hidden: true,
                    itemId: 'labNo',
                    width: 190,
                    fieldLabel: 'Lab No',
                    name: 'labNo'
                }
            ]
        }
    ]

});