/*
 * File: app/view/Shifts.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.view.Shifts', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.shifts',

    requires: [
        'CarePortal.view.ShiftsViewModel',
        'Ext.view.Table',
        'Ext.grid.column.Column',
        'Ext.toolbar.Paging'
    ],

    viewModel: {
        type: 'shifts'
    },
    height: 382,
    itemId: 'shiftsGrid',
    width: 842,
    columnLines: true,
    store: 'ShiftsStore',

    columns: [
        {
            xtype: 'gridcolumn',
            width: 46,
            dataIndex: 'ID',
            text: 'ID'
        },
        {
            xtype: 'gridcolumn',
            width: 88,
            dataIndex: 'CashPoint',
            text: 'CashPoint'
        },
        {
            xtype: 'gridcolumn',
            width: 70,
            dataIndex: 'ShiftNo',
            text: 'Shift No'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'Cashier',
            text: 'Cashier'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'StartDate',
            text: 'Start Date'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'StartTime',
            text: 'Start Time'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'EndDate',
            text: 'End Date'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'EndTime',
            text: 'End Time'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'Status',
            text: 'Status'
        }
    ],
    dockedItems: [
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            width: 360,
            displayInfo: true,
            store: 'ShiftsStore'
        }
    ]

});