/*
 * File: app/view/StockLevels.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.view.StockLevels', {
    extend: 'Ext.form.Panel',
    alias: 'widget.stocklevels',

    requires: [
        'CarePortal.view.StockLevelsViewModel',
        'Ext.grid.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.view.Table',
        'Ext.grid.column.Column',
        'Ext.toolbar.Paging'
    ],

    viewModel: {
        type: 'stocklevels'
    },
    style: 'background-color: #d9f2e6;',
    bodyStyle: 'background-color: #d9f2e6;',
    url: 'data/getDataFunctions.php?task=adjustStock',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'gridpanel',
            frame: true,
            height: 680,
            itemId: 'levelsGrid',
            minWidth: 600,
            width: 900,
            columnLines: true,
            store: 'StockLevelsStore',
            dockedItems: [
                {
                    xtype: 'fieldset',
                    dock: 'top',
                    height: 45,
                    padding: 0,
                    style: 'background-color: #d9f2e6;',
                    width: 100,
                    layout: 'absolute',
                    items: [
                        {
                            xtype: 'textfield',
                            x: 5,
                            y: 5,
                            itemId: 'txtSearchProducts',
                            width: 255,
                            emptyText: 'Search by Partcode, Description'
                        },
                        {
                            xtype: 'combobox',
                            x: 265,
                            y: 5,
                            width: 235
                        },
                        {
                            xtype: 'button',
                            x: 515,
                            y: 5,
                            width: 135,
                            iconCls: 'x-fa fa-search',
                            text: 'Search'
                        }
                    ]
                },
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 360,
                    displayInfo: true,
                    store: 'StockLevelsStore'
                }
            ],
            columns: [
                {
                    xtype: 'gridcolumn',
                    width: 59,
                    dataIndex: 'ID',
                    text: 'ID'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Store',
                    text: 'Store'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'PartCode',
                    text: 'Stock Id'
                },
                {
                    xtype: 'gridcolumn',
                    width: 217,
                    dataIndex: 'Item_Description',
                    text: 'Description'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Quantity',
                    text: 'Quantity'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Reorderlevel',
                    text: 'Reorderlevel'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Category',
                    text: 'Category'
                }
            ]
        },
        {
            xtype: 'container',
            flex: 1,
            itemId: 'levelsForm',
            style: 'background-color: #d9f2e6;',
            items: [
                {
                    xtype: 'fieldset',
                    style: 'background-color: #d9f2e6;',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            flex: 0,
                            itemId: 'id',
                            fieldLabel: 'ID',
                            labelStyle: 'color:green; font-weight:bold;',
                            name: 'ID'
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            itemId: 'unititemcategory',
                            fieldLabel: 'Category',
                            labelStyle: 'color:green; font-weight:bold;',
                            name: 'Category'
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            itemId: 'itemnumber',
                            fieldLabel: 'Part Code',
                            labelStyle: 'color:green; font-weight:bold;',
                            name: 'PartCode'
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            itemId: 'description',
                            fieldLabel: 'Description',
                            labelStyle: 'color:green; font-weight:bold;',
                            name: 'Item_Description'
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            itemId: 'loccode',
                            fieldLabel: 'Location',
                            labelStyle: 'color:green; font-weight:bold;',
                            name: 'Store'
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            itemId: 'quantity',
                            fieldLabel: 'Quantity',
                            labelStyle: 'color:green; font-weight:bold;',
                            name: 'Quantity'
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            itemId: 'reorderlevel',
                            fieldLabel: 'Reorder level',
                            labelStyle: 'color:green; font-weight:bold;',
                            name: 'ReorderLevel'
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'comment',
                            fieldLabel: 'Comment',
                            labelStyle: 'color:green; font-weight:bold;',
                            name: 'Comment'
                        },
                        {
                            xtype: 'button',
                            itemId: 'saveStockAdjustments',
                            iconCls: 'x-fa fa-save',
                            text: 'Save Stock Adjustments'
                        }
                    ]
                }
            ]
        }
    ]

});