/*
 * File: app/view/Suppliers.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.view.Suppliers', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.suppliers',

    requires: [
        'CarePortal.view.SuppliersViewModel',
        'Ext.view.Table',
        'Ext.grid.column.Column',
        'Ext.toolbar.Paging',
        'Ext.selection.RowModel'
    ],

    viewModel: {
        type: 'suppliers'
    },
    height: 253,
    itemId: 'supplierslist',
    width: 505,
    columnLines: true,
    store: 'SuppliersStore',

    columns: [
        {
            xtype: 'gridcolumn',
            dataIndex: 'ID',
            text: 'ID'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'SupID',
            text: 'Supplier ID'
        },
        {
            xtype: 'gridcolumn',
            width: 242,
            dataIndex: 'Description',
            text: 'Description'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'AmountOwed',
            text: 'Amount Owed'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'AmountPaid',
            text: 'Amount Paid'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'Amount',
            text: 'Amount Due'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'ledger',
            text: 'Ledger'
        }
    ],
    dockedItems: [
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            width: 360,
            displayInfo: true,
            store: 'SuppliersStore'
        }
    ],
    selModel: {
        selType: 'rowmodel'
    }

});