/*
 * File: app/view/Suppliers.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.view.Suppliers', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.suppliers',

    requires: [
        'CarePortal.view.SuppliersViewModel',
        'Ext.view.Table',
        'Ext.toolbar.Paging',
        'Ext.selection.RowModel',
        'Ext.grid.column.Column'
    ],

    viewModel: {
        type: 'suppliers'
    },
    itemId: 'supplierslist',
    columnLines: true,
    store: 'SuppliersStore',

    dockedItems: [
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            width: 360,
            displayInfo: true,
            store: 'SuppliersStore'
        }
    ],
    selModel: {
        selType: 'rowmodel'
    },
    columns: [
        {
            xtype: 'gridcolumn',
            dataIndex: 'supplierid',
            text: 'Supplierid'
        },
        {
            xtype: 'gridcolumn',
            width: 233,
            dataIndex: 'suppname',
            text: 'Suppname'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'address',
            text: 'Address'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'postalCode',
            text: 'Postal Code'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'street',
            text: 'Street'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'city',
            text: 'City'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'country',
            text: 'Country'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'mobile',
            text: 'Mobile'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'telephone',
            text: 'Telephone'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'email',
            text: 'Email'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'supptype',
            text: 'Supptype'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'salesperson',
            text: 'Salesperson'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'currcode',
            text: 'Currcode'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'suppliersince',
            text: 'Suppliersince'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'paymentterms',
            text: 'Paymentterms'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'lastpaid',
            text: 'Lastpaid'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'lastpaiddate',
            text: 'Lastpaiddate'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'bankact',
            text: 'Bankact'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'bankref',
            text: 'Bankref'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'bankpartics',
            text: 'Bankpartics'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'remittance',
            text: 'Remittance'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'taxgroupid',
            text: 'Taxgroupid'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'taxref',
            text: 'Taxref'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'web',
            text: 'Web'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'currBalance',
            text: 'Curr Balance'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'accountReceivable',
            text: 'Account Receivable'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'accountPayable',
            text: 'Account Payable'
        }
    ]

});