/*
 * File: app/view/SystemAdmin.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.view.SystemAdmin', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.systemadmin',

    requires: [
        'CarePortal.view.SystemAdminViewModel',
        'CarePortal.view.UserManagement',
        'Ext.tab.Tab',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Column',
        'Ext.selection.RowModel',
        'Ext.grid.plugin.RowEditing',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.toolbar.Spacer',
        'Ext.Img',
        'Ext.form.field.File',
        'Ext.toolbar.Paging',
        'Ext.form.FieldContainer'
    ],

    viewModel: {
        type: 'systemadmin'
    },
    activeTab: 0,
    defaultListenerScope: true,

    items: [
        {
            xtype: 'panel',
            title: 'User Management',
            items: [
                {
                    xtype: 'usermanagement'
                }
            ]
        },
        {
            xtype: 'panel',
            title: 'Data Management',
            items: [
                {
                    xtype: 'panel',
                    height: 662,
                    items: [
                        {
                            xtype: 'container',
                            height: 52,
                            padding: 10,
                            items: [
                                {
                                    xtype: 'button',
                                    width: 217,
                                    text: 'Discharge Previous Pending OP'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: 52,
                            padding: 10,
                            items: [
                                {
                                    xtype: 'button',
                                    width: 217,
                                    text: 'Clear Old Pending Prescriptions'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: 52,
                            padding: 10,
                            items: [
                                {
                                    xtype: 'button',
                                    width: 217,
                                    text: 'Clear Old Pending Lab Request'
                                }
                            ]
                        },
                        {
                            xtype: 'gridpanel',
                            height: 345,
                            style: 'border-style:solid;',
                            bodyBorder: true,
                            title: 'NHIF Rates',
                            columnLines: true,
                            store: 'NhifRatesStore',
                            dockedItems: [
                                {
                                    xtype: 'container',
                                    dock: 'top',
                                    height: 42,
                                    padding: 5,
                                    width: 100,
                                    items: [
                                        {
                                            xtype: 'button',
                                            width: 217,
                                            text: 'Update Rates'
                                        }
                                    ]
                                }
                            ],
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    width: 46,
                                    dataIndex: 'ID',
                                    text: 'ID'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 240,
                                    dataIndex: 'RateType',
                                    text: 'Rate Type'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'RateValue',
                                    text: 'Rate Value',
                                    editor: {
                                        xtype: 'textfield'
                                    }
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'RateCalc',
                                    text: 'Rate Calc',
                                    editor: {
                                        xtype: 'textfield'
                                    }
                                }
                            ],
                            selModel: {
                                selType: 'rowmodel'
                            },
                            plugins: [
                                {
                                    ptype: 'rowediting'
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            padding: '10 100 100 100',
            bodyBorder: true,
            bodyPadding: 10,
            title: 'Company Details',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'form',
                    flex: 1,
                    animateShadow: true,
                    fixed: true,
                    shadow: 'drop',
                    shadowOffset: 10,
                    shim: true,
                    frame: true,
                    height: 880,
                    ui: 'default-framed',
                    bodyBorder: true,
                    frameHeader: false,
                    items: [
                        {
                            xtype: 'fieldset',
                            animateShadow: true,
                            shadow: 'frame',
                            shadowOffset: 10,
                            height: 94,
                            layout: {
                                type: 'hbox',
                                align: 'stretchmax',
                                padding: 10
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    itemId: 'CompanyName',
                                    width: 679,
                                    fieldLabel: 'Company Name',
                                    labelAlign: 'top',
                                    labelStyle: 'font-weight:bold;',
                                    name: 'CompanyName',
                                    fieldStyle: 'background-color:#d2d2ff;font-weight:bold; color:maroon;'
                                },
                                {
                                    xtype: 'tbspacer',
                                    flex: 1
                                },
                                {
                                    xtype: 'image',
                                    height: 63,
                                    width: 93,
                                    src: 'icons%5Clogo2.jpg'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            padding: 10,
                            title: 'General Information',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    margin: '0 10 0 0',
                                    layout: 'form',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            itemId: 'PhysicalAddress',
                                            fieldLabel: 'Address',
                                            labelStyle: 'font-weight:bold;',
                                            name: 'PhysicalAddress',
                                            fieldStyle: 'font-weight:bold; color:maroon;',
                                            emptyText: 'Physical Address'
                                        },
                                        {
                                            xtype: 'textfield',
                                            itemId: 'Address',
                                            name: 'Address',
                                            fieldStyle: 'font-weight:bold; color:maroon;',
                                            emptyText: 'Postal Address'
                                        },
                                        {
                                            xtype: 'textfield',
                                            itemId: 'Postal',
                                            name: 'Postal',
                                            fieldStyle: 'font-weight:bold; color:maroon;',
                                            emptyText: 'Postal Code'
                                        },
                                        {
                                            xtype: 'textfield',
                                            itemId: 'County',
                                            name: 'County',
                                            fieldStyle: 'font-weight:bold; color:maroon;',
                                            emptyText: 'County'
                                        },
                                        {
                                            xtype: 'textfield',
                                            itemId: 'mflCode',
                                            fieldLabel: 'MFL Code',
                                            labelStyle: 'font-weight:bold;',
                                            name: 'mflCode',
                                            fieldStyle: 'font-weight:bold; color:maroon;'
                                        },
                                        {
                                            xtype: 'textfield',
                                            itemId: 'vatNo',
                                            fieldLabel: 'Vat No',
                                            labelStyle: 'font-weight:bold;',
                                            name: 'vatNo',
                                            fieldStyle: 'font-weight:bold; color:maroon;'
                                        },
                                        {
                                            xtype: 'textfield',
                                            itemId: 'pinNo',
                                            fieldLabel: 'Pin No',
                                            labelStyle: 'font-weight:bold;',
                                            name: 'pinNo',
                                            fieldStyle: 'font-weight:bold; color:maroon;'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    layout: 'form',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            itemId: 'Tel',
                                            fieldLabel: 'Phone',
                                            labelStyle: 'font-weight:bold;',
                                            name: 'Tel',
                                            fieldStyle: 'font-weight:bold; color:maroon;'
                                        },
                                        {
                                            xtype: 'textfield',
                                            itemId: 'Mobile',
                                            fieldLabel: 'Mobile',
                                            labelStyle: 'font-weight:bold;',
                                            name: 'Mobile',
                                            fieldStyle: 'font-weight:bold; color:maroon;'
                                        },
                                        {
                                            xtype: 'textfield',
                                            itemId: 'Email',
                                            fieldLabel: 'Email',
                                            labelStyle: 'font-weight:bold;',
                                            name: 'Email',
                                            fieldStyle: 'font-weight:bold; color:maroon;'
                                        },
                                        {
                                            xtype: 'textfield',
                                            itemId: 'Website',
                                            fieldLabel: 'Website',
                                            labelStyle: 'font-weight:bold;',
                                            name: 'Website',
                                            fieldStyle: 'font-weight:bold; color:maroon;'
                                        },
                                        {
                                            xtype: 'filefield',
                                            itemId: 'logoPath',
                                            fieldLabel: 'Logo',
                                            labelStyle: 'font-weight:bold;',
                                            name: 'logoPath',
                                            fieldStyle: 'font-weight:bold; color:maroon;'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            layout: {
                                type: 'hbox',
                                align: 'stretch',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    width: 195,
                                    text: 'Save'
                                }
                            ]
                        }
                    ],
                    listeners: {
                        afterrender: 'onFormAfterRender'
                    }
                }
            ]
        },
        {
            xtype: 'panel',
            title: 'Menus Management',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    scrollable: 'both',
                    columnLines: true,
                    store: 'MenuItemsStore',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'Nr',
                            text: 'Nr'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'SortNr',
                            text: 'Sort Nr'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'GroupID',
                            text: 'Group Id'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'GroupName',
                            text: 'Group Name'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 188,
                            dataIndex: 'Name',
                            text: 'Name'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 276,
                            dataIndex: 'Url',
                            text: 'Url'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'IS_Visible',
                            text: 'Is Visible'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'Status',
                            text: 'Status'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 206,
                            dataIndex: 'S_image',
                            text: 'S Image'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'Type',
                            text: 'Type'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'PageID',
                            text: 'Page Id'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'DispType',
                            text: 'Disp Type'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'MenuItemsStore'
                        },
                        {
                            xtype: 'fieldcontainer',
                            dock: 'top',
                            height: 44,
                            padding: 5,
                            width: 100,
                            layout: {
                                type: 'hbox',
                                align: 'stretch',
                                padding: 2
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    margin: '0 50 0 5',
                                    width: 230,
                                    emptyText: 'Search Menus'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'cmdNewMenu',
                                    margin: '0 0 0 50',
                                    width: 133,
                                    iconCls: 'x-fa fa-plus',
                                    text: 'New Menu'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],

    onFormAfterRender: function(component, eOpts) {
        component.down("#CompanyName").setValue(localStorage.getItem('CompanyName'));
        component.down("#PhysicalAddress").setValue(localStorage.getItem('PhysicalAddress'));
        component.down("#Address").setValue(localStorage.getItem('Address'));
        component.down("#Postal").setValue(localStorage.getItem('Postal'));
        component.down("#County").setValue(localStorage.getItem('County'));
        component.down("#mflCode").setValue(localStorage.getItem('mflCode'));
        component.down("#vatNo").setValue(localStorage.getItem('vatNo'));
        component.down("#pinNo").setValue(localStorage.getItem('pinNo'));
        component.down("#Tel").setValue(localStorage.getItem('Phone'));
        component.down("#Mobile").setValue(localStorage.getItem('Mobile'));
        component.down("#Email").setValue(localStorage.getItem('Email'));
        component.down("#Website").setValue(localStorage.getItem('Website'));
        component.down("#logoPath").setValue(localStorage.getItem('logoPath'));

    }

});