/*
 * File: app/view/VitalsLists.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.view.VitalsLists', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.vitalslists',

    requires: [
        'CarePortal.view.VitalsListsViewModel',
        'Ext.view.Table',
        'Ext.grid.column.Column'
    ],

    viewModel: {
        type: 'vitalslists'
    },
    store: 'VitalsStore',

    columns: [
        {
            xtype: 'gridcolumn',
            hidden: true,
            dataIndex: 'ID',
            text: 'ID'
        },
        {
            xtype: 'gridcolumn',
            width: 98,
            dataIndex: 'VitalsDate',
            text: 'Date'
        },
        {
            xtype: 'gridcolumn',
            width: 96,
            dataIndex: 'VitalsTime',
            text: 'Time'
        },
        {
            xtype: 'gridcolumn',
            hidden: true,
            dataIndex: 'Pid',
            text: 'Pid'
        },
        {
            xtype: 'gridcolumn',
            hidden: true,
            dataIndex: 'EncounterNo',
            text: 'Encounter No'
        },
        {
            xtype: 'gridcolumn',
            width: 72,
            dataIndex: 'Temperature',
            text: 'Temp'
        },
        {
            xtype: 'gridcolumn',
            width: 54,
            dataIndex: 'Pulse',
            text: 'Pulse'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'Respiration',
            text: 'Respiration'
        },
        {
            xtype: 'gridcolumn',
            width: 60,
            dataIndex: 'Systolic',
            text: 'Systolic'
        },
        {
            xtype: 'gridcolumn',
            width: 62,
            dataIndex: 'Diastolic',
            text: 'Diastolic'
        },
        {
            xtype: 'gridcolumn',
            width: 64,
            dataIndex: 'Weight',
            text: 'Weight'
        },
        {
            xtype: 'gridcolumn',
            width: 58,
            dataIndex: 'Height',
            text: 'Height'
        },
        {
            xtype: 'gridcolumn',
            width: 47,
            dataIndex: 'Bmi',
            text: 'Bmi'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'HeadCircumference',
            text: 'Head Circumference'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'Spo2',
            text: 'Spo2'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'HTC',
            text: 'Htc'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'Notes',
            text: 'Notes'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'InputUser',
            text: 'Input User'
        }
    ]

});