/*
 * File: app/view/WardOccupancyViewController.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.view.WardOccupancyViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.wardoccupancy',

    onWardsItemClick: function(item) {
        var view = this.getView();
        var wardsMenu = this.lookupReference('wardsButton').menu;

        //Ext.Msg.alert('Test',item.value);

        view.store.load({
            params:{
                wardId:item.value
            }
        });

        var d = new Date();
        this.lookupReference('wardTitle').setValue(item.text +" Ward");
        this.lookupReference('currDate').setValue(d.toLocaleString());
        this.lookupReference('wardID').setValue(item.value);

        this.getWaitingList(item.value);

    },

    getWaitingList: function(wrdNr) {
        //vitalsPanel = Ext.create('CarePortal.view.Vitals', {});
        //waitingListPanel=this.getWardoccupancy().down("#waitingList");
        waitingListPanel=this.lookupReference('waitingList');


        var waitingStore=Ext.data.StoreManager.lookup("WaitingListStore");

        waitingStore.load({
            params: {
                wardNo:wrdNr
            },
            callback: function(records, operation, success) {
                var totalRecs=records.length;
               // Ext.Msg.alert('Test','Total Records are '+totalRecs);
                if(totalRecs>0){
                      var tpl=new Ext.XTemplate(
                            '<tpl for=".">',
                                '<li style="border:1px solid #1faf2e; border-radius: 5px;cursor: pointer;list-style: none outside;color:white; padding:1px;background-color:#354e75; margin:1px;" id={EncounterNr}>{Pid} {Names} {EncounterNr}</li>',
                            '</tpl>'
                        );
                        var data = [];

                        waitingStore.each(function(record) {
                            data.push(record.getData());


                        });

                        tpl.overwrite(waitingListPanel.body,data);
                }else{
                    var data2 = [];
                    var tpl2=new Ext.XTemplate(
                        '<Table id=notes>',
                        '<tr><td colspan=5 class=titles><br>Waiting List is Empty</br></td></tr></table>');
                    tpl2.overwrite(waitingListPanel.body,data2);
                }

            },
            scope: this
        });

    },

    openRegistration: function(view, rowIndex, colIndex, item, e, record, row) {
        //http://192.168.1.243/litein/modules/registration_admission/aufnahme_pass.php?sid=fdoueeor5klkqq32iq1irl8kh7&ntid=false&lang=en&target=search&fwd_nr=10472908
        var sid="?sid=fdoueeor5klkqq32iq1irl8kh7&ntid=false&lang=en";
        var encNo=record.get('encounterNr');
        var url="../registration_admission/aufnahme_pass.php"+sid+"&target=search&fwd_nr=10472908";// +encNo;

        window.location.href = url;
    },

    onWardsListLoad: function(store, records, successful, operation, eOpts) {
        //Ext.Msg.alert('Test','Test');
        var me = this,
            references = me.getReferences(),
            view = me.getView(),
            items = [],
            columns = [ view.nameColumn ];


        // iterate each record in the store
        store.each(function (metaRecord) {
            items.push(Ext.apply({
                text  : metaRecord.data.Name,
                value : metaRecord.data.Nr,
                listeners : {
                    click : me.onWardsItemClick,
                    scope : me
                }
            }));

        });
        references.wardsButton.menu.add(items);

    }

});
