/*
 * File: app/model/AnesthesiaCharts.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.model.AnesthesiaCharts', {
    extend: 'Ext.data.Model',
    alias: 'model.anesthesiacharts',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'ID'
        },
        {
            mapping: 'encounter_nr',
            name: 'encounter_nr'
        },
        {
            mapping: 'item_description',
            name: 'item_description'
        },
        {
            mapping: '1',
            name: '1'
        },
        {
            mapping: '2',
            name: '2'
        },
        {
            mapping: '3',
            name: '3'
        },
        {
            mapping: '4',
            name: '4'
        },
        {
            mapping: '5',
            name: '5'
        },
        {
            mapping: '6',
            name: '6'
        },
        {
            mapping: '7',
            name: '7'
        },
        {
            mapping: '8',
            name: '8'
        },
        {
            mapping: '9',
            name: '9'
        },
        {
            mapping: '10',
            name: '10'
        },
        {
            mapping: '11',
            name: '11'
        },
        {
            mapping: '12',
            name: '12'
        }
    ]
});