/*
 * File: app/model/Appointments.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.model.Appointments', {
    extend: 'Ext.data.Model',
    alias: 'model.appointments',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'pid'
        },
        {
            name: 'encounter_nr'
        },
        {
            name: 'names'
        },
        {
            name: 'date_birth'
        },
        {
            name: 'sex'
        },
        {
            name: 'date'
        },
        {
            name: 'time'
        },
        {
            name: 'to_dept_nr'
        },
        {
            name: 'to_personell_nr'
        },
        {
            name: 'purpose'
        },
        {
            name: 'urgency'
        },
        {
            name: 'remind'
        },
        {
            name: 'remind_email'
        },
        {
            name: 'remind_phone'
        },
        {
            name: 'appt_status'
        },
        {
            name: 'cancel_by'
        },
        {
            name: 'cancel_date'
        },
        {
            name: 'cancel_reason'
        }
    ]
});