/*
 * File: app/model/InventoryItems.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.model.InventoryItems', {
    extend: 'Ext.data.Model',
    alias: 'model.inventoryitems',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'PartCode'
        },
        {
            name: 'Item_Description'
        },
        {
            name: 'Item_Full_Description'
        },
        {
            name: 'Purchasing_Class'
        },
        {
            name: 'Category'
        },
        {
            name: 'Unit_Price'
        },
        {
            name: 'buying_price'
        },
        {
            name: 'Reorderlevel'
        },
        {
            name: 'Minimum'
        },
        {
            name: 'Maximum'
        },
        {
            name: 'Unit_Measure'
        },
        {
            name: 'Item_Status'
        },
        {
            name: 'Gl_Sales_Acct'
        },
        {
            name: 'Gl_Inventory_Acct'
        },
        {
            name: 'Gl_CostOfSales_Acct'
        },
        {
            name: 'PresLevel'
        },
        {
            name: 'PresNHIF'
        },
        {
            name: 'Purchasing_Unit'
        },
        {
            name: 'Qty'
        },
        {
            name: 'SalesAreas'
        },
        {
            name: 'MoreInfo'
        },
        {
            name: 'IsStockItem'
        },
        {
            name: 'ChargeInAdmission'
        }
    ]
});