/*
 * File: app/model/StaffsList.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.model.StaffsList', {
    extend: 'Ext.data.Model',
    alias: 'model.staffslist',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'ID'
        },
        {
            name: 'staff_name'
        },
        {
            name: 'JobTitle'
        },
        {
            name: 'Department'
        },
        {
            name: 'EnterRequest'
        },
        {
            name: 'EnterResults'
        },
        {
            name: 'ViewResults'
        },
        {
            name: 'TakeSamples'
        },
        {
            name: 'ReceiveSamples'
        },
        {
            name: 'VerifyResults'
        },
        {
            name: 'ApproveResults'
        }
    ]
});