/*
 * File: app/model/Suppliers.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.model.Suppliers', {
    extend: 'Ext.data.Model',
    alias: 'model.suppliers',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'supplierid'
        },
        {
            name: 'suppname'
        },
        {
            name: 'address'
        },
        {
            name: 'postalCode'
        },
        {
            name: 'street'
        },
        {
            name: 'city'
        },
        {
            name: 'country'
        },
        {
            name: 'mobile'
        },
        {
            name: 'telephone'
        },
        {
            name: 'email'
        },
        {
            name: 'supptype'
        },
        {
            name: 'salesperson'
        },
        {
            name: 'currcode'
        },
        {
            name: 'suppliersince'
        },
        {
            name: 'paymentterms'
        },
        {
            name: 'lastpaid'
        },
        {
            name: 'lastpaiddate'
        },
        {
            name: 'bankact'
        },
        {
            name: 'bankref'
        },
        {
            name: 'bankpartics'
        },
        {
            name: 'remittance'
        },
        {
            name: 'taxgroupid'
        },
        {
            name: 'taxref'
        },
        {
            name: 'web'
        },
        {
            name: 'currBalance'
        },
        {
            name: 'accountReceivable'
        },
        {
            name: 'accountPayable'
        }
    ]
});