/*
 * File: app/model/UserRoles.js
 *
 * This file was generated by Sencha Architect version 4.3.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarePortal.model.UserRoles', {
    extend: 'Ext.data.Model',
    alias: 'model.userroles',

    requires: [
        'Ext.data.field.Field'
    ],

    idProperty: 'ID',

    fields: [
        {
            name: 'Module'
        },
        {
            name: 'ID'
        },
        {
            name: 'Role'
        },
        {
            name: 'RoleName'
        },
        {
            name: 'View'
        },
        {
            name: 'Edit'
        },
        {
            name: 'Delete'
        }
    ]
});